[workspace]
resolver = "2"
members = [
    "crates/keyguard-zip-c",
    "crates/keyguard-zip-core",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.94.0"
license-file = "../../../LICENSE"
repository = "https://github.com/AChep/keyguard-app"

[workspace.dependencies]
self_cell = "=1.3.0"
sha2 = "=0.11.0"
zeroize = "=1.9.0"
zip = { version = "=8.6.0", default-features = false, features = [
    "aes-crypto",
    "deflate-flate2-zlib-rs",
] }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "deny"
unused_lifetimes = "deny"
unused_qualifications = "warn"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
undocumented_unsafe_blocks = "deny"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = true

[profile.dev.package."*"]
opt-level = 2
