name: "GitHub Submit PR"
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  commit-message:
    description: 'Commit message'
    required: true
  commit-branch:
    description: 'Commit branch'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Check if any changes"
      id: check-changes
      run: |
        has_changes=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
        echo "$has_changes"
        echo "HAS_CHANGES=$has_changes" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v1.0.3
      if: ${{ startsWith(steps.check-changes.outputs.HAS_CHANGES, 'true') }}
      with:
        github_token: "${{ inputs.github-token }}"
        add_timestamp: false
        commit_prefix: "[AUTO] "
        commit_message: ${{ inputs.commit-message }}
        force: true
        target_branch: ${{ inputs.commit-branch }}
    - name: Create pull request
      uses: devops-infra/action-pull-request@v1.0.2
      if: ${{ startsWith(steps.check-changes.outputs.HAS_CHANGES, 'true') }}
      with:
        github_token: "${{ inputs.github-token }}"
        source_branch: ${{ inputs.commit-branch }}
        target_branch: master
        assignee: AChep
        label: "robot,enhancement"
        title: ${{ inputs.commit-message }}
