name: "GitHub Submit PR"
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  commit-message:
    description: 'Commit message'
    required: true
  commit-branch:
    description: 'Commit branch'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Check if any changes"
      id: check-changes
      run: |
        has_changes=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
        echo "$has_changes"
        echo "HAS_CHANGES=$has_changes" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Configure Git and Commit
      if: ${{ steps.check-changes.outputs.HAS_CHANGES == 'true' }}
      shell: bash
      run: |
        git config --global user.name "keyguard-bot"
        git config --global user.email "keyguard-bot@artemchep.com"

        # Checkout target branch (carrying over current changes)
        # -B forces creation or reset of the branch
        git checkout -B "${{ inputs.commit-branch }}"

        # Commit
        git add .
        git commit -m "[AUTO] ${{ inputs.commit-message }}"

        # Push
        git push origin "${{ inputs.commit-branch }}" --force
    - name: Create Pull Request
      if: ${{ steps.check-changes.outputs.HAS_CHANGES == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        # Create PR using GitHub CLI
        # We use '|| true' or checks to prevent failure if PR already exists
        gh pr create \
          --base master \
          --head "${{ inputs.commit-branch }}" \
          --title "${{ inputs.commit-message }}" \
          --body "Automated PR created by GitHub Action" \
          --assignee "AChep" \
          --label "robot,enhancement" \
          || echo "PR likely already exists, skipping creation."
