package com.artemchep.keyguard.common.model

fun attachmentPreviewKindByFileName(
    fileName: String,
): AttachmentPreviewKind? {
    val extension = fileName.attachmentPreviewFileExtension()
    if (extension in ATTACHMENT_PREVIEW_IMAGE_EXTENSIONS) {
        return AttachmentPreviewKind.Image
    }
    if (extension in ATTACHMENT_PREVIEW_MARKDOWN_EXTENSIONS) {
        return AttachmentPreviewKind.Markdown
    }

    val name = fileName.attachmentPreviewFileName().lowercase()
    if (name.isKnownTextAttachmentPreviewFileName() || extension in ATTACHMENT_PREVIEW_TEXT_EXTENSIONS) {
        return AttachmentPreviewKind.Text
    }

    return null
}

fun isAttachmentPreviewSupported(
    fileName: String,
): Boolean = attachmentPreviewKindByFileName(fileName) != null

fun isMarkdownAttachmentPreview(
    fileName: String,
): Boolean = fileName.attachmentPreviewFileExtension() in ATTACHMENT_PREVIEW_MARKDOWN_EXTENSIONS

internal fun String.attachmentPreviewFileName(): String {
    val separatorIndex = indexOfLast { it == '/' || it == '\\' }
    return if (separatorIndex != -1 && separatorIndex < length - 1) {
        substring(separatorIndex + 1)
    } else {
        this
    }
}

internal fun String.attachmentPreviewFileExtension(): String? {
    val separatorIndex = indexOfLast { it == '/' || it == '\\' }
    val extensionIndex = indexOfLast { it == '.' }
    return if (extensionIndex != -1 && extensionIndex > separatorIndex && extensionIndex < length - 1) {
        substring(extensionIndex + 1).lowercase()
    } else {
        null
    }
}

private val ATTACHMENT_PREVIEW_IMAGE_EXTENSIONS = setOf(
    "png",
    "jpg",
    "jpeg",
    "gif",
    "bmp",
    "webp",
    "heic",
    "heif",
)

private val ATTACHMENT_PREVIEW_MARKDOWN_EXTENSIONS = setOf(
    "md",
    "markdown",
)

private val ATTACHMENT_PREVIEW_TEXT_EXTENSIONS = setOf(
    "ada",
    "adb",
    "ads",
    "applescript",
    "as",
    "asc",
    "ascx",
    "asm",
    "asmx",
    "asp",
    "aspx",
    "atom",
    "bas",
    "bash",
    "bashrc",
    "bat",
    "bbcolors",
    "bdsgroup",
    "bdsproj",
    "bib",
    "bowerrc",
    "c",
    "cbl",
    "cc",
    "cer",
    "cfc",
    "cfg",
    "cfm",
    "cfml",
    "cgi",
    "cjs",
    "clj",
    "cls",
    "cmake",
    "cmd",
    "cnf",
    "cob",
    "coffee",
    "coffeekup",
    "command",
    "conf",
    "config",
    "cpp",
    "cpt",
    "cpy",
    "crt",
    "cs",
    "csh",
    "cson",
    "csr",
    "css",
    "csslintrc",
    "csv",
    "ctl",
    "cts",
    "curlrc",
    "cxx",
    "dart",
    "dfm",
    "diff",
    "dockerfile",
    "dockerignore",
    "dof",
    "dpk",
    "dproj",
    "dtd",
    "eco",
    "editorconfig",
    "ejs",
    "el",
    "emacs",
    "eml",
    "ent",
    "env",
    "erb",
    "erl",
    "eslintignore",
    "eslintrc",
    "ex",
    "exs",
    "f",
    "f03",
    "f77",
    "f90",
    "f95",
    "fish",
    "for",
    "fpp",
    "frm",
    "ftn",
    "gemrc",
    "gitattributes",
    "gitconfig",
    "gitignore",
    "gitkeep",
    "gitmodules",
    "go",
    "gpp",
    "gradle",
    "groovy",
    "groupproj",
    "grunit",
    "gtmpl",
    "gvimrc",
    "h",
    "haml",
    "hbs",
    "hgignore",
    "hh",
    "hpp",
    "hrl",
    "hs",
    "hta",
    "htaccess",
    "htc",
    "htm",
    "html",
    "htpasswd",
    "hxx",
    "iced",
    "inc",
    "ini",
    "ino",
    "int",
    "irbrc",
    "itcl",
    "itermcolors",
    "itk",
    "jade",
    "java",
    "jhtm",
    "jhtml",
    "js",
    "jscsrc",
    "jshintignore",
    "jshintrc",
    "json",
    "json5",
    "jsonc",
    "jsonld",
    "jsp",
    "jspx",
    "jsx",
    "key",
    "ksh",
    "kt",
    "kts",
    "less",
    "lhs",
    "lisp",
    "log",
    "ls",
    "lsp",
    "lua",
    "m",
    "mak",
    "makefile",
    "map",
    "master",
    "mdown",
    "mdwn",
    "mdx",
    "metadata",
    "mht",
    "mhtml",
    "mjs",
    "mk",
    "mkd",
    "mkdn",
    "mkdown",
    "ml",
    "mli",
    "mm",
    "mts",
    "mxml",
    "nfm",
    "nfo",
    "njk",
    "noon",
    "npmignore",
    "npmrc",
    "nvmrc",
    "ops",
    "pas",
    "pasm",
    "patch",
    "pbxproj",
    "pch",
    "pem",
    "pg",
    "php",
    "php3",
    "php4",
    "php5",
    "phpt",
    "phtml",
    "pir",
    "pl",
    "pm",
    "pmc",
    "pod",
    "pot",
    "properties",
    "props",
    "ps1",
    "pt",
    "pub",
    "pug",
    "py",
    "r",
    "rake",
    "rakefile",
    "rb",
    "rdoc",
    "rdoc_options",
    "resx",
    "rhtml",
    "rjs",
    "rlib",
    "rmd",
    "ron",
    "rs",
    "rss",
    "rst",
    "rtf",
    "rvmrc",
    "rxml",
    "s",
    "sass",
    "scala",
    "scm",
    "scss",
    "seestyle",
    "sh",
    "shtml",
    "sls",
    "spec",
    "sql",
    "ss",
    "sss",
    "st",
    "strings",
    "sty",
    "styl",
    "stylus",
    "sub",
    "sublime-build",
    "sublime-commands",
    "sublime-completions",
    "sublime-keymap",
    "sublime-macro",
    "sublime-menu",
    "sublime-project",
    "sublime-settings",
    "sublime-workspace",
    "sv",
    "svc",
    "svg",
    "swift",
    "t",
    "tcl",
    "tcsh",
    "terminal",
    "tex",
    "text",
    "textile",
    "tg",
    "tmlanguage",
    "tmtheme",
    "tmpl",
    "toml",
    "tpl",
    "ts",
    "tsv",
    "tsx",
    "tt",
    "tt2",
    "ttml",
    "txt",
    "v",
    "vb",
    "vbs",
    "vh",
    "vhd",
    "vhdl",
    "vim",
    "viminfo",
    "vimrc",
    "vue",
    "webapp",
    "wxml",
    "wxss",
    "x-php",
    "xaml",
    "xht",
    "xhtml",
    "xml",
    "xs",
    "xsd",
    "xsl",
    "xslt",
    "yaml",
    "yml",
    "zsh",
    "zshrc",
) + ATTACHMENT_PREVIEW_MARKDOWN_EXTENSIONS

private fun String.isKnownTextAttachmentPreviewFileName(): Boolean =
    this == ".env" ||
        startsWith(".env.") ||
        this == ".editorconfig" ||
        this == ".gitattributes" ||
        this == ".gitignore" ||
        this == ".dockerignore" ||
        this == "dockerfile" ||
        startsWith("dockerfile.") ||
        this == "containerfile" ||
        startsWith("containerfile.") ||
        this == "makefile" ||
        startsWith("makefile.") ||
        this == "readme" ||
        this == "license" ||
        this == "licence" ||
        this == "copying" ||
        this == "notice" ||
        this == "gemfile" ||
        this == "rakefile"
