name: "Setup Gradle"
inputs:
  java-distribution:
    description: 'Java Distribution'
    required: true
    default: 'temurin'
  java-version:
    description: 'Java Version'
    required: true
    default: '21'
  cache-write-only:
    description: 'Cache Write Only'
    required: true
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: "Setup JDK 21"
      id: setup-java
      uses: actions/setup-java@v5
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
    - name: "Setup Gradle"
      uses: gradle/actions/setup-gradle@v5
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
      with:
        cache-write-only: ${{ inputs.cache-write-only }}
