package com.artemchep.keyguard.crypto

import com.artemchep.keyguard.common.model.GpgKeyConfig
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpExportPublicKeyRequest
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpPublicKey
import kotlinx.io.Buffer
import kotlinx.io.readByteArray
import org.bouncycastle.openpgp.PGPPublicKeyRingCollection
import org.bouncycastle.openpgp.PGPUtil
import org.bouncycastle.openpgp.operator.jcajce.JcaKeyFingerprintCalculator
import java.io.ByteArrayInputStream
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

class NativeGpgPublicKeyExportJvmTest {
    private val service = NativeGpgOpenPgpService()
    private val generated by lazy {
        NativeGpgKeyGenerator.generate(
            GpgKeyConfig.Modern(userId = "Public export <export@test.invalid>"),
        )
    }

    @Test
    fun `binary export is a parseable public-key certificate`() {
        val output = Buffer()

        service.exportPublicKey(
            GpgOpenPgpExportPublicKeyRequest(
                publicKey = GpgOpenPgpPublicKey(generated.publicKeyArmored),
                output = output,
                armored = false,
            ),
        )

        val exported = output.readByteArray()
        val collection = PGPPublicKeyRingCollection(
            ByteArrayInputStream(exported),
            JcaKeyFingerprintCalculator(),
        )
        val rings = collection.keyRings.asSequence().toList()
        assertEquals(1, rings.size)
        assertEquals(
            generated.fingerprint,
            rings.single().publicKey.fingerprint.toHexString(),
        )
    }

    @Test
    fun `armored export is canonical and parseable`() {
        val output = Buffer()

        service.exportPublicKey(
            GpgOpenPgpExportPublicKeyRequest(
                publicKey = GpgOpenPgpPublicKey(generated.publicKeyArmored),
                output = output,
            ),
        )

        val exported = output.readByteArray().decodeToString()
        assertTrue(exported.startsWith("-----BEGIN PGP PUBLIC KEY BLOCK-----"))
        val collection = PGPPublicKeyRingCollection(
            PGPUtil.getDecoderStream(ByteArrayInputStream(exported.encodeToByteArray())),
            JcaKeyFingerprintCalculator(),
        )
        assertEquals(1, collection.keyRings.asSequence().count())
    }

    @Test
    fun `invalid input writes no output`() {
        val output = Buffer()

        assertFailsWith<IllegalArgumentException> {
            service.exportPublicKey(
                GpgOpenPgpExportPublicKeyRequest(
                    publicKey = GpgOpenPgpPublicKey("not an OpenPGP public key"),
                    output = output,
                    armored = false,
                ),
            )
        }

        assertEquals(0L, output.size)
    }

    @Test
    fun `multiple certificates are rejected before writing`() {
        val output = Buffer()

        assertFailsWith<IllegalArgumentException> {
            service.exportPublicKey(
                GpgOpenPgpExportPublicKeyRequest(
                    publicKey = GpgOpenPgpPublicKey(
                        generated.publicKeyArmored + "\n" + generated.publicKeyArmored,
                    ),
                    output = output,
                    armored = false,
                ),
            )
        }

        assertEquals(0L, output.size)
    }

    private fun ByteArray.toHexString(): String = joinToString(separator = "") { byte ->
        byte.toUByte().toString(radix = 16).padStart(length = 2, padChar = '0')
    }.uppercase()
}
