package com.artemchep.keyguard.crypto

import com.artemchep.keyguard.common.model.GeneratedGpgKey
import com.artemchep.keyguard.common.model.GpgKeyConfig
import com.artemchep.keyguard.common.model.GpgKeyVersion
import com.artemchep.keyguard.common.model.GpgKeyExpiry
import com.artemchep.keyguard.common.service.crypto.GpgKeyImportRequest
import com.artemchep.keyguard.common.service.crypto.GpgKeyImportResult
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpDecryptTextRequest
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpEncryptTextRequest
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpPrivateKey
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpPublicKey
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpSignTextRequest
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpVerificationStatus
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpVerifyDetachedTextRequest
import com.artemchep.keyguard.common.service.crypto.GpgPublicKeyParseResult
import org.bouncycastle.bcpg.HashAlgorithmTags
import org.bouncycastle.bcpg.SymmetricKeyAlgorithmTags
import org.bouncycastle.openpgp.PGPPublicKeyRingCollection
import org.bouncycastle.openpgp.PGPSecretKey
import org.bouncycastle.openpgp.PGPSecretKeyRing
import org.bouncycastle.openpgp.PGPSecretKeyRingCollection
import org.bouncycastle.openpgp.PGPSignature
import org.bouncycastle.openpgp.PGPSignatureList
import org.bouncycastle.openpgp.PGPUtil
import org.bouncycastle.openpgp.jcajce.JcaPGPObjectFactory
import org.bouncycastle.openpgp.operator.jcajce.JcaKeyFingerprintCalculator
import org.bouncycastle.openpgp.operator.jcajce.JcaPGPDigestCalculatorProviderBuilder
import org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentVerifierBuilderProvider
import org.bouncycastle.openpgp.operator.jcajce.JcePBESecretKeyEncryptorBuilder
import java.io.ByteArrayInputStream
import java.security.Security
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertTrue

/**
 * Permanent BC 1.84 differential coverage for OpenPGP write behavior.
 *
 * OpenPGP output is randomized, so this suite compares domain behavior and
 * cross-implementation interoperability rather than serialized bytes, including
 * SEIPDv1/MDC for legacy recipients and RFC 9580 SEIPDv2/AEAD for v6 recipients.
 */
class OpenPgpWriteBouncyCastleDifferentialTest {
    private val nativeService = NativeGpgOpenPgpService()
    private val bcService = BcGpgOpenPgpServiceTestOracle()
    private val nativeImport = NativeGpgKeyImportService
    private val bcImport = BcGpgKeyImportServiceTestOracle(
        publicKeyParser = NativeGpgPublicKeyParser,
        metadataResolver = NativeGpgKeyMetadataResolver,
    )
    private val parser = NativeGpgPublicKeyParser

    private val modernConfig = GpgKeyConfig.Modern(
        userId = "OpenPGP write differential <openpgp-write-differential@test.invalid>",
        expiry = GpgKeyExpiry.Never,
    )
    private val bcGenerated by lazy {
        BcGpgKeyGeneratorTestOracle().generate(modernConfig)
    }

    @BeforeTest
    fun installPinnedTestOracle() {
        if (Security.getProvider(gpgBouncyCastleProvider.name) == null) {
            Security.addProvider(gpgBouncyCastleProvider)
        }
        assertEquals("1.84", gpgBouncyCastleProvider.versionStr)
    }

    @Test
    fun `BC encrypted MDC message decrypts through native`() {
        val key = bcGenerated
        val plaintext = "BC to native OpenPGP encryption"
        val encrypted = bcService.encryptText(
            GpgOpenPgpEncryptTextRequest(
                candidateRevocationKeys = emptyList(),
                text = plaintext,
                publicKeys = listOf(key.publicKey()),
            ),
        )

        val decrypted = nativeService.decryptText(
            GpgOpenPgpDecryptTextRequest(
                encryptedText = encrypted,
                privateKeys = listOf(key.privateKey()),
            ),
        )

        assertEquals(plaintext, decrypted.text)
    }

    @Test
    fun `native MDC message decrypts through BC`() {
        val key = bcGenerated
        val plaintext = "native to BC OpenPGP encryption"
        val encrypted = nativeService.encryptText(
            GpgOpenPgpEncryptTextRequest(
                candidateRevocationKeys = emptyList(),
                text = plaintext,
                publicKeys = listOf(key.publicKey()),
            ),
        )

        val decrypted = bcService.decryptText(
            GpgOpenPgpDecryptTextRequest(
                encryptedText = encrypted,
                privateKeys = listOf(key.privateKey()),
            ),
        )

        assertEquals(plaintext, decrypted.text)
    }

    @Test
    fun `BC detached signature verifies through native`() {
        val key = bcGenerated
        val text = "BC signature verified by native"
        val signature = bcService.signTextDetached(
            GpgOpenPgpSignTextRequest(
                text = text,
                privateKey = key.privateKey(),
                candidateRevocationKeys = emptyList(),
            ),
        )

        val request = GpgOpenPgpVerifyDetachedTextRequest(
            text = text,
            signature = signature,
            publicKeys = listOf(key.publicKey()),
        )
        val expected = bcService.verifyDetachedText(request)
        val result = nativeService.verifyDetachedText(request)

        assertEquals(GpgOpenPgpVerificationStatus.VALID, expected.status)
        assertEquals(expected.status, result.status)
        assertEquals(expected.fingerprint, result.fingerprint)
        assertEquals(expected.keyId, result.keyId)
    }

    @Test
    fun `native detached signature verifies with BC public operations`() {
        val key = bcGenerated
        val text = "native signature verified by BC"
        val signature = nativeService.signTextDetached(
            GpgOpenPgpSignTextRequest(
                text = text,
                privateKey = key.privateKey(),
                candidateRevocationKeys = emptyList(),
            ),
        )

        assertTrue(verifyDetachedWithBc(text, signature, key.publicKeyArmored))
    }

    @Test
    fun `native and BC import outcomes preserve the same domain contract`() {
        val publicOnly = publicKeyArmoredOf(bcGenerated.privateKeyArmored)
        val cases = listOf(
            GpgKeyImportRequest(content = ""),
            GpgKeyImportRequest(content = bcGenerated.privateKeyArmored),
            GpgKeyImportRequest(content = publicOnly),
        )

        cases.forEach { request ->
            assertEquals(
                expected = bcImport.import(request).shape(),
                actual = nativeImport.import(request).shape(),
                message = request.content.lineSequence().firstOrNull().orEmpty(),
            )
        }
    }

    @Test
    fun `native and BC generated certificates have equivalent structural policy`() {
        val configs = listOf(
            modernConfig,
            modernConfig.copy(version = GpgKeyVersion.V6),
            GpgKeyConfig.Rsa(
                userId = "OpenPGP write RSA differential <openpgp-write-rsa@test.invalid>",
                length = GpgKeyConfig.RsaLength.B3072,
                expiry = GpgKeyExpiry.Never,
            ),
            GpgKeyConfig.Rsa(
                userId = "OpenPGP v6 RSA differential <openpgp-v6-rsa@test.invalid>",
                length = GpgKeyConfig.RsaLength.B3072,
                expiry = GpgKeyExpiry.Never,
                version = GpgKeyVersion.V6,
            ),
        )

        configs.forEach { config ->
            val bc = BcGpgKeyGeneratorTestOracle().generate(config)
            val native = NativeGpgKeyGenerator.generate(config)
            assertEquals(certificateShape(bc), certificateShape(native), config.type.title)
            val text = "Cross-implementation certificate version ${config.version}"
            val signature = nativeService.signTextDetached(
                GpgOpenPgpSignTextRequest(
                    text = text,
                    privateKey = native.privateKey(),
                    candidateRevocationKeys = emptyList(),
                ),
            )
            assertTrue(verifyDetachedWithBc(text, signature, native.publicKeyArmored))
            verifyCertificateWithBc(native.publicKeyArmored)
        }
    }

    @Test
    fun `v6 signatures encryption and protected imports interoperate with BC`() {
        val configs = listOf(
            modernConfig.copy(version = GpgKeyVersion.V6),
            GpgKeyConfig.Rsa(
                userId = modernConfig.userId,
                length = GpgKeyConfig.RsaLength.B3072,
                expiry = GpgKeyExpiry.Never,
                version = GpgKeyVersion.V6,
            ),
        )
        for (config in configs) {
            val keys = listOf(
                NativeGpgKeyGenerator.generate(config),
                BcGpgKeyGeneratorTestOracle().generate(config),
            )
            for (key in keys) {
                val text = "RFC 9580 cross-implementation message"
                val signature = bcService.signTextDetached(
                    GpgOpenPgpSignTextRequest(
                        text = text,
                        privateKey = key.privateKey(),
                        candidateRevocationKeys = emptyList(),
                    ),
                )
                assertEquals(
                    GpgOpenPgpVerificationStatus.VALID,
                    nativeService.verifyDetachedText(
                        GpgOpenPgpVerifyDetachedTextRequest(
                            text = text,
                            signature = signature,
                            publicKeys = listOf(key.publicKey()),
                        ),
                    ).status,
                )
                for ((encryptor, decryptor) in listOf(nativeService to bcService, bcService to nativeService)) {
                    val encrypted = encryptor.encryptText(
                        GpgOpenPgpEncryptTextRequest(
                            candidateRevocationKeys = emptyList(),
                            text = text,
                            publicKeys = listOf(key.publicKey()),
                        ),
                    )
                    assertEquals(
                        text,
                        decryptor.decryptText(
                            GpgOpenPgpDecryptTextRequest(
                                encryptedText = encrypted,
                                privateKeys = listOf(key.privateKey()),
                            ),
                        ).text,
                    )
                }
                for (armor in listOf(key.publicKeyArmored, key.privateKeyArmored)) {
                    val imported = assertIs<GpgKeyImportResult.Success>(
                        nativeImport.import(GpgKeyImportRequest(content = armor)),
                    )
                    assertEquals(key.fingerprint, imported.gpgKey.fingerprint)
                    assertEquals(
                        key.fingerprint,
                        assertIs<GpgKeyImportResult.Success>(nativeImport.import(
                            GpgKeyImportRequest(content = imported.gpgKey.publicKeyArmored),
                        )).gpgKey.fingerprint,
                    )
                }
                val ring = PGPSecretKeyRingCollection(
                    PGPUtil.getDecoderStream(ByteArrayInputStream(key.privateKeyArmored.encodeToByteArray())),
                    JcaKeyFingerprintCalculator(),
                ).keyRings.next()
                val passphrase = "v6 import test passphrase"
                val digests = JcaPGPDigestCalculatorProviderBuilder().build()
                val protected = PGPSecretKeyRing(ring.secretKeys.asSequence().map { secretKey ->
                    PGPSecretKey(
                        secretKey.extractPrivateKeyEmptyPassphrase(),
                        secretKey.publicKey,
                        digests.get(HashAlgorithmTags.SHA1),
                        secretKey.isMasterKey,
                        JcePBESecretKeyEncryptorBuilder(
                            SymmetricKeyAlgorithmTags.AES_256,
                            digests.get(HashAlgorithmTags.SHA256),
                        ).setProvider(gpgBouncyCastleProvider).build(passphrase.toCharArray()),
                    )
                }.toList()).armored()
                assertIs<GpgKeyImportResult.NeedsPassphrase>(
                    nativeImport.import(GpgKeyImportRequest(content = protected)),
                )
                val unprotected = assertIs<GpgKeyImportResult.Success>(nativeImport.import(
                    GpgKeyImportRequest(content = protected, passphrase = passphrase),
                ))
                assertEquals(key.fingerprint, unprotected.gpgKey.fingerprint)
                assertIs<GpgKeyImportResult.Success>(nativeImport.import(
                    GpgKeyImportRequest(content = unprotected.gpgKey.privateKeyArmored),
                ))
            }
        }
    }

    private fun verifyCertificateWithBc(armor: String) {
        val ring = PGPPublicKeyRingCollection(
            PGPUtil.getDecoderStream(ByteArrayInputStream(armor.encodeToByteArray())),
            JcaKeyFingerprintCalculator(),
        ).keyRings.next()
        val primary = ring.publicKey
        val verifier = JcaPGPContentVerifierBuilderProvider().setProvider(gpgBouncyCastleProvider)
        primary.getSignaturesOfType(PGPSignature.DIRECT_KEY).forEach { signature ->
            signature.init(verifier, primary)
            assertTrue(signature.verifyCertification(primary))
        }
        primary.userIDs.forEach { identity ->
            primary.getSignaturesForID(identity).forEach { signature ->
                signature.init(verifier, primary)
                assertTrue(signature.verifyCertification(identity, primary))
            }
        }
        ring.publicKeys.asSequence().drop(1).forEach { subkey ->
            assertEquals(primary.version, subkey.version)
            subkey.getSignaturesOfType(PGPSignature.SUBKEY_BINDING).forEach { signature ->
                signature.init(verifier, primary)
                assertTrue(signature.verifyCertification(primary, subkey))
                signature.hashedSubPackets.embeddedSignatures.forEach { backSignature ->
                    backSignature.init(verifier, subkey)
                    assertTrue(backSignature.verifyCertification(primary, subkey))
                }
            }
        }
    }

    private fun certificateShape(generated: GeneratedGpgKey): CertificateShape {
        val parsed = assertIs<GpgPublicKeyParseResult.Success>(
            parser.parse(generated.publicKeyArmored),
        ).keys.single()
        return CertificateShape(
            algorithm = parsed.algorithm,
            bitStrength = parsed.bitStrength,
            userIds = parsed.userIds,
            canSign = parsed.canSign,
            canEncrypt = parsed.canEncrypt,
            subkeys = parsed.subKeys.map { subkey ->
                SubkeyShape(
                    algorithm = subkey.algorithm,
                    bitStrength = subkey.bitStrength,
                    canSign = subkey.canSign,
                    canEncrypt = subkey.canEncrypt,
                )
            },
        )
    }

    private fun verifyDetachedWithBc(
        text: String,
        signatureArmored: String,
        publicKeyArmored: String,
    ): Boolean {
        val factory = JcaPGPObjectFactory(
            PGPUtil.getDecoderStream(
                ByteArrayInputStream(signatureArmored.encodeToByteArray()),
            ),
        )
        val signatures = generateSequence { factory.nextObject() }
            .filterIsInstance<PGPSignatureList>()
            .first()
        val signature = signatures[0]
        val certificates = PGPPublicKeyRingCollection(
            PGPUtil.getDecoderStream(ByteArrayInputStream(publicKeyArmored.encodeToByteArray())),
            JcaKeyFingerprintCalculator(),
        )
        val publicKey = requireNotNull(certificates.getPublicKey(signature.keyID))
        signature.init(
            JcaPGPContentVerifierBuilderProvider().setProvider(gpgBouncyCastleProvider),
            publicKey,
        )
        val data = text.encodeToByteArray()
        signature.update(data, 0, data.size)
        return signature.verify()
    }

    private fun publicKeyArmoredOf(secretKeyArmored: String): String {
        val rings = PGPSecretKeyRingCollection(
            PGPUtil.getDecoderStream(ByteArrayInputStream(secretKeyArmored.encodeToByteArray())),
            JcaKeyFingerprintCalculator(),
        )
        return rings.keyRings.next().toCertificate().armored()
    }

    private fun GeneratedGpgKey.privateKey() = GpgOpenPgpPrivateKey(
        armored = privateKeyArmored,
        preferredFingerprint = fingerprint,
    )

    private fun GeneratedGpgKey.publicKey() = GpgOpenPgpPublicKey(publicKeyArmored)

    private fun GpgKeyImportResult.shape(): ImportShape = when (this) {
        is GpgKeyImportResult.Success -> ImportShape(
            outcome = "success",
            detail = gpgKey.fingerprint,
            hasPrivateKey = gpgKey.privateKeyArmored.isNotEmpty(),
        )

        is GpgKeyImportResult.NeedsPassphrase -> ImportShape(
            outcome = "needs-passphrase",
            detail = formatLabel,
            hasPrivateKey = false,
        )

        is GpgKeyImportResult.Error -> ImportShape(
            outcome = "error",
            detail = reason.name,
            hasPrivateKey = false,
        )
    }

    private data class ImportShape(
        val outcome: String,
        val detail: String,
        val hasPrivateKey: Boolean,
    )

    private data class CertificateShape(
        val algorithm: String,
        val bitStrength: Int?,
        val userIds: List<String>,
        val canSign: Boolean,
        val canEncrypt: Boolean,
        val subkeys: List<SubkeyShape>,
    )

    private data class SubkeyShape(
        val algorithm: String,
        val bitStrength: Int?,
        val canSign: Boolean,
        val canEncrypt: Boolean,
    )
}
