package com.artemchep.keyguard.crypto

import com.artemchep.keyguard.common.model.GeneratedGpgKey
import com.artemchep.keyguard.common.model.GpgKeyConfig
import com.artemchep.keyguard.common.model.GpgKeyExpiry
import com.artemchep.keyguard.common.service.crypto.GpgKeyImportRequest
import com.artemchep.keyguard.common.service.crypto.GpgKeyImportResult
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpDecryptTextRequest
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpEncryptTextRequest
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpPrivateKey
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpPublicKey
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpSignTextRequest
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpVerificationStatus
import com.artemchep.keyguard.common.service.crypto.GpgOpenPgpVerifyDetachedTextRequest
import com.artemchep.keyguard.common.service.crypto.GpgPublicKeyParseResult
import org.bouncycastle.openpgp.PGPPublicKeyRingCollection
import org.bouncycastle.openpgp.PGPSecretKeyRingCollection
import org.bouncycastle.openpgp.PGPSignatureList
import org.bouncycastle.openpgp.PGPUtil
import org.bouncycastle.openpgp.jcajce.JcaPGPObjectFactory
import org.bouncycastle.openpgp.operator.jcajce.JcaKeyFingerprintCalculator
import org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentVerifierBuilderProvider
import java.io.ByteArrayInputStream
import java.security.Security
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertTrue

/**
 * Permanent BC 1.84 differential coverage for OpenPGP write behavior.
 *
 * OpenPGP output is randomized, so this suite compares domain behavior and
 * cross-implementation interoperability rather than serialized bytes. OCB is
 * intentionally covered by GnuPG fixtures; these encryption cases freeze the
 * compatible SEIPDv1/MDC branch produced for the BC-generated recipient.
 */
class OpenPgpWriteBouncyCastleDifferentialTest {
    private val nativeService = NativeGpgOpenPgpService
    private val bcService = BcGpgOpenPgpServiceTestOracle()
    private val nativeImport = NativeGpgKeyImportService
    private val bcImport = BcGpgKeyImportServiceTestOracle(
        publicKeyParser = NativeGpgPublicKeyParser,
        metadataResolver = NativeGpgKeyMetadataResolver,
    )
    private val parser = NativeGpgPublicKeyParser

    private val modernConfig = GpgKeyConfig.Modern(
        userId = "OpenPGP write differential <openpgp-write-differential@test.invalid>",
        expiry = GpgKeyExpiry.Never,
    )
    private val bcGenerated by lazy {
        BcGpgKeyGeneratorTestOracle().generate(modernConfig)
    }

    @BeforeTest
    fun installPinnedTestOracle() {
        if (Security.getProvider(gpgBouncyCastleProvider.name) == null) {
            Security.addProvider(gpgBouncyCastleProvider)
        }
        assertEquals("1.84", gpgBouncyCastleProvider.versionStr)
    }

    @Test
    fun `BC encrypted MDC message decrypts through native`() {
        val key = bcGenerated
        val plaintext = "BC to native OpenPGP encryption"
        val encrypted = bcService.encryptText(
            GpgOpenPgpEncryptTextRequest(
                text = plaintext,
                publicKeys = listOf(key.publicKey()),
            ),
        )

        val decrypted = nativeService.decryptText(
            GpgOpenPgpDecryptTextRequest(
                encryptedText = encrypted,
                privateKeys = listOf(key.privateKey()),
            ),
        )

        assertEquals(plaintext, decrypted.text)
    }

    @Test
    fun `native MDC message decrypts through BC`() {
        val key = bcGenerated
        val plaintext = "native to BC OpenPGP encryption"
        val encrypted = nativeService.encryptText(
            GpgOpenPgpEncryptTextRequest(
                text = plaintext,
                publicKeys = listOf(key.publicKey()),
            ),
        )

        val decrypted = bcService.decryptText(
            GpgOpenPgpDecryptTextRequest(
                encryptedText = encrypted,
                privateKeys = listOf(key.privateKey()),
            ),
        )

        assertEquals(plaintext, decrypted.text)
    }

    @Test
    fun `BC detached signature verifies through native`() {
        val key = bcGenerated
        val text = "BC signature verified by native"
        val signature = bcService.signTextDetached(
            GpgOpenPgpSignTextRequest(text = text, privateKey = key.privateKey()),
        )

        val request = GpgOpenPgpVerifyDetachedTextRequest(
            text = text,
            signature = signature,
            publicKeys = listOf(key.publicKey()),
        )
        val expected = bcService.verifyDetachedText(request)
        val result = nativeService.verifyDetachedText(request)

        assertEquals(GpgOpenPgpVerificationStatus.VALID, expected.status)
        assertEquals(expected.status, result.status)
        assertEquals(expected.fingerprint, result.fingerprint)
        assertEquals(expected.keyId, result.keyId)
    }

    @Test
    fun `native detached signature verifies with BC public operations`() {
        val key = bcGenerated
        val text = "native signature verified by BC"
        val signature = nativeService.signTextDetached(
            GpgOpenPgpSignTextRequest(text = text, privateKey = key.privateKey()),
        )

        assertTrue(verifyDetachedWithBc(text, signature, key.publicKeyArmored))
    }

    @Test
    fun `native and BC import outcomes preserve the same domain contract`() {
        val publicOnly = publicKeyArmoredOf(bcGenerated.privateKeyArmored)
        val cases = listOf(
            GpgKeyImportRequest(content = ""),
            GpgKeyImportRequest(content = bcGenerated.privateKeyArmored),
            GpgKeyImportRequest(content = publicOnly),
        )

        cases.forEach { request ->
            assertEquals(
                expected = bcImport.import(request).shape(),
                actual = nativeImport.import(request).shape(),
                message = request.content.lineSequence().firstOrNull().orEmpty(),
            )
        }
    }

    @Test
    fun `native and BC generated certificates have equivalent structural policy`() {
        val configs = listOf(
            modernConfig,
            GpgKeyConfig.Rsa(
                userId = "OpenPGP write RSA differential <openpgp-write-rsa@test.invalid>",
                length = GpgKeyConfig.RsaLength.B3072,
                expiry = GpgKeyExpiry.Never,
            ),
        )

        configs.forEach { config ->
            val bc = BcGpgKeyGeneratorTestOracle().generate(config)
            val native = NativeGpgKeyGenerator.generate(config)
            assertEquals(certificateShape(bc), certificateShape(native), config.type.title)
        }
    }

    private fun certificateShape(generated: GeneratedGpgKey): CertificateShape {
        val parsed = assertIs<GpgPublicKeyParseResult.Success>(
            parser.parse(generated.publicKeyArmored),
        ).keys.single()
        return CertificateShape(
            algorithm = parsed.algorithm,
            bitStrength = parsed.bitStrength,
            userIds = parsed.userIds,
            canSign = parsed.canSign,
            canEncrypt = parsed.canEncrypt,
            subkeys = parsed.subKeys.map { subkey ->
                SubkeyShape(
                    algorithm = subkey.algorithm,
                    bitStrength = subkey.bitStrength,
                    canSign = subkey.canSign,
                    canEncrypt = subkey.canEncrypt,
                )
            },
        )
    }

    private fun verifyDetachedWithBc(
        text: String,
        signatureArmored: String,
        publicKeyArmored: String,
    ): Boolean {
        val factory = JcaPGPObjectFactory(
            PGPUtil.getDecoderStream(
                ByteArrayInputStream(signatureArmored.encodeToByteArray()),
            ),
        )
        val signatures = generateSequence { factory.nextObject() }
            .filterIsInstance<PGPSignatureList>()
            .first()
        val signature = signatures[0]
        val certificates = PGPPublicKeyRingCollection(
            PGPUtil.getDecoderStream(ByteArrayInputStream(publicKeyArmored.encodeToByteArray())),
            JcaKeyFingerprintCalculator(),
        )
        val publicKey = requireNotNull(certificates.getPublicKey(signature.keyID))
        signature.init(
            JcaPGPContentVerifierBuilderProvider().setProvider(gpgBouncyCastleProvider),
            publicKey,
        )
        val data = text.encodeToByteArray()
        signature.update(data, 0, data.size)
        return signature.verify()
    }

    private fun publicKeyArmoredOf(secretKeyArmored: String): String {
        val rings = PGPSecretKeyRingCollection(
            PGPUtil.getDecoderStream(ByteArrayInputStream(secretKeyArmored.encodeToByteArray())),
            JcaKeyFingerprintCalculator(),
        )
        return rings.keyRings.next().toCertificate().armored()
    }

    private fun GeneratedGpgKey.privateKey() = GpgOpenPgpPrivateKey(
        armored = privateKeyArmored,
        preferredFingerprint = fingerprint,
    )

    private fun GeneratedGpgKey.publicKey() = GpgOpenPgpPublicKey(publicKeyArmored)

    private fun GpgKeyImportResult.shape(): ImportShape = when (this) {
        is GpgKeyImportResult.Success -> ImportShape(
            outcome = "success",
            detail = gpgKey.fingerprint,
            hasPrivateKey = gpgKey.privateKeyArmored.isNotEmpty(),
        )

        is GpgKeyImportResult.NeedsPassphrase -> ImportShape(
            outcome = "needs-passphrase",
            detail = formatLabel,
            hasPrivateKey = false,
        )

        is GpgKeyImportResult.Error -> ImportShape(
            outcome = "error",
            detail = reason.name,
            hasPrivateKey = false,
        )
    }

    private data class ImportShape(
        val outcome: String,
        val detail: String,
        val hasPrivateKey: Boolean,
    )

    private data class CertificateShape(
        val algorithm: String,
        val bitStrength: Int?,
        val userIds: List<String>,
        val canSign: Boolean,
        val canEncrypt: Boolean,
        val subkeys: List<SubkeyShape>,
    )

    private data class SubkeyShape(
        val algorithm: String,
        val bitStrength: Int?,
        val canSign: Boolean,
        val canEncrypt: Boolean,
    )
}
