version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "cargo"
    directory: "/util/crypto/rust"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
