// Generated by scripts/generate_keyguard_icons.py. Edit artwork/icons/keyguard-*.svg instead.
package com.artemchep.keyguard.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

internal object KeyguardVectors {
    val ConnectionTest: ImageVector by lazy {
        icon(name = "KeyguardConnectionTest", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M6 3v4M10 3v4M4 7h8v3a4 4 0 0 1-8 0ZM8 14v3a4 4 0 0 0 4 4h2M15 13l2 2 5-6"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val Decrypt: ImageVector by lazy {
        icon(name = "KeyguardDecrypt", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M9 21H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l5 5h-5V3M8 12h1"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M16 15v-3a3 3 0 0 1 6 0M14 15h6a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-6a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1Z"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val Encrypt: ImageVector by lazy {
        icon(name = "KeyguardEncrypt", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M9 21H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l5 5h-5V3M8 12h1"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M15 15v-2a2 2 0 0 1 4 0v2M14 15h6a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-6a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1Z"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val FileSign: ImageVector by lazy {
        icon(name = "KeyguardFileSign", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M9 21H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l5 5v2M11 3v5h5M8 12h2"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("m18 12 3 3-6 6h-3v-3ZM16.5 13.5l3 3"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val FileVerify: ImageVector by lazy {
        icon(name = "KeyguardFileVerify", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M9 21H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l5 5v2M11 3v5h5M8 12h2M13 17l3 3 6-6"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val GpgKeySelected: ImageVector by lazy {
        icon(name = "KeyguardGpgKeySelected", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M6 3h12a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M6 3h12a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z M13 11.328a3 3 0 1 0-2 0V19h5v-2h-3v-1h2v-2h-2Z"),
                fill = SolidColor(Color.Black),
            )
            addPath(
                pathData = addPathNodes("M13 8.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"),
                fill = SolidColor(Color.Black),
            )
        }
    }

    val GpgKey: ImageVector by lazy {
        icon(name = "KeyguardGpgKey", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M6 3h12a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M14.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0ZM12 11v7h3M12 15h2"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val GpgSearch: ImageVector by lazy {
        icon(name = "KeyguardGpgSearch", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M9 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM9 7h8v2M13 7v2"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M19.5 16a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM18.5 19l3 3"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val GpgVerifyIdentity: ImageVector by lazy {
        icon(name = "KeyguardGpgVerifyIdentity", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M10 19H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4M3 7l9 6 9-6M14 18l2.5 2.5L22 15"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val PwnedPassword: ImageVector by lazy {
        icon(name = "KeyguardPwnedPassword", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M9 20H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v3"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M8 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM12 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM16 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"),
                fill = SolidColor(Color.Black),
            )
            addPath(
                pathData = addPathNodes("M18 13v3"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M19 20a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"),
                fill = SolidColor(Color.Black),
            )
        }
    }

    val Screenshot: ImageVector by lazy {
        icon(name = "KeyguardScreenshot", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M3 8V3h5M16 3h5v5M21 16v5h-5M8 21H3v-5M7 7h10v10H7ZM7 14l3-3 3 3 2-2 2 2"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val SshKey: ImageVector by lazy {
        icon(name = "KeyguardSshKey", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M7 20H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4M6.5 8 9 10.5 6.5 13"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M14.5 16a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm0 0H21v2M18 16v3"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val StoredKey: ImageVector by lazy {
        icon(name = "KeyguardStoredKey", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M4 13h16l2 6v2H2v-2ZM2 18h20"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M9 6.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM9 6.5h9V9M14 6.5V9"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val UnusableGpgKey: ImageVector by lazy {
        icon(name = "KeyguardUnusableGpgKey", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M9 3h9a2 2 0 0 1 2 2v10M4 9v10a2 2 0 0 0 2 2h9M10 5.8a3 3 0 0 1 4.2 4.2M12 12v6h3M3 3l18 18"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    val WeakGpgKey: ImageVector by lazy {
        icon(name = "KeyguardWeakGpgKey", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M10 21H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v4M12 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0ZM10 10v6h2M18 13v3"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M19 20a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"),
                fill = SolidColor(Color.Black),
            )
        }
    }

    val YubiKey: ImageVector by lazy {
        icon(name = "KeyguardYubiKey", autoMirror = false) {
            addPath(
                pathData = addPathNodes("M9 8V3h6v5M7 8h10v10a3 3 0 0 1-3 3h-4a3 3 0 0 1-3-3Z"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
            addPath(
                pathData = addPathNodes("M14.5 14a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Z"),
                fill = null,
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
            )
        }
    }

    private fun icon(
        name: String,
        autoMirror: Boolean,
        block: ImageVector.Builder.() -> Unit,
    ): ImageVector = ImageVector.Builder(
        name = name,
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
        autoMirror = autoMirror,
    ).apply(block).build()
}
