package com.artemchep.keyguard.common.service.relays.api.forwardemail

import com.artemchep.keyguard.common.io.IO
import com.artemchep.keyguard.common.io.ioEffect
import com.artemchep.keyguard.common.model.GeneratorContext
import com.artemchep.keyguard.common.service.relays.api.EmailRelay
import com.artemchep.keyguard.common.service.relays.api.EmailRelaySchema
import com.artemchep.keyguard.common.service.text.Base64Service
import com.artemchep.keyguard.feature.confirmation.ConfirmationRoute
import com.artemchep.keyguard.feature.localization.TextHolder
import com.artemchep.keyguard.res.Res
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.header
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.http.contentType
import io.ktor.http.isSuccess
import kotlinx.collections.immutable.ImmutableMap
import kotlinx.collections.immutable.persistentMapOf
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.kodein.di.DirectDI
import org.kodein.di.instance

class ForwardEmailEmailRelay(
    private val base64Service: Base64Service,
    private val httpClient: HttpClient,
) : EmailRelay {
    companion object {
        private const val KEY_API_KEY = "apiKey"
        private const val HINT_API_KEY = "XXXX"
        private const val KEY_DOMAIN = "domain"
        private const val HINT_DOMAIN = "mailsire.com"
    }

    override val type = "ForwardEmail"

    override val name = "Forward Email"

    override val docUrl =
        "https://bitwarden.com/help/generator/#tab-forward-email-3Uj911RtQsJD9OAhUuoKrz"

    override val schema = persistentMapOf(
        KEY_API_KEY to EmailRelaySchema(
            title = TextHolder.Res(Res.strings.api_key),
            hint = TextHolder.Value(HINT_API_KEY),
            type = ConfirmationRoute.Args.Item.StringItem.Type.Token,
            canBeEmpty = false,
        ),
        KEY_DOMAIN to EmailRelaySchema(
            title = TextHolder.Res(Res.strings.domain),
            hint = TextHolder.Value(HINT_DOMAIN),
            canBeEmpty = false,
        ),
    )

    constructor(directDI: DirectDI) : this(
        base64Service = directDI.instance(),
        httpClient = directDI.instance(),
    )

    override fun generate(
        context: GeneratorContext,
        config: ImmutableMap<String, String>,
    ): IO<String> = ioEffect {
        val apiKey = requireNotNull(config[KEY_API_KEY]) {
            "API key is required for creating an email alias."
        }
        val domain = requireNotNull(config[KEY_DOMAIN]) {
            "Domain is required for creating an email alias."
        }

        val endpoint = "https://api.forwardemail.net/v1/domains/$domain/aliases"
        val response = httpClient
            .post(endpoint) {
                val token = base64Service.encodeToString("$apiKey:")
                header("Authorization", "Basic $token")

                val body = ForwardEmailRequest(
                    description = context.host
                        ?: "Generated by Keyguard",
                )
                contentType(ContentType.Application.Json)
                setBody(body)
            }
        require(response.status.isSuccess()) {
            // Example of an error:
            // {
            //   "statusCode": 401,
            //   "error": "Unauthorized",
            //   "message": "Invalid API token."
            // }
            val message = runCatching {
                val result = response
                    .body<JsonObject>()
                result["message"]?.jsonPrimitive?.content
                    ?: result["error"]?.jsonPrimitive?.content
            }.getOrNull()
            message ?: HttpStatusCode.fromValue(response.status.value).description
        }
        val result = response
            .body<JsonObject>()
        val aliasName = result["name"]?.jsonPrimitive?.content
        val aliasDomain = runCatching {
            result["domain"]?.jsonObject?.get("name")?.jsonPrimitive?.content
        }.getOrNull() ?: domain
        requireNotNull(aliasName) {
            "Email alias is missing from the response. " +
                    "Please report this to the developer."
        }
        "$aliasName@$aliasDomain"
    }

    @Serializable
    private data class ForwardEmailRequest(
        val description: String,
    )
}
