[package]
name = "keyguard-zxcvbn-core"
description = "Native password strength estimation for Keyguard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[dependencies]
zxcvbn.workspace = true

[lints]
workspace = true
