[package]
name = "common-gpg-agent-rust"
version.workspace = true
edition = "2021"
rust-version.workspace = true
description = "Shared Rust utilities for Keyguard GPG agent binaries"
license-file.workspace = true
repository.workspace = true
publish = false

[dependencies]
prost.workspace = true

[build-dependencies]
prost-build.workspace = true

[lints.clippy]
undocumented_unsafe_blocks = "deny"
