package com.artemchep.keyguard.feature.navigation.state

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import com.artemchep.keyguard.common.service.clipboard.ClipboardEventBus
import com.artemchep.keyguard.common.service.clipboard.ClipboardService
import com.artemchep.keyguard.common.usecase.GetDebugScreenDelay
import com.artemchep.keyguard.common.usecase.GetScreenState
import com.artemchep.keyguard.common.usecase.PutScreenState
import com.artemchep.keyguard.common.usecase.ShowMessage
import com.artemchep.keyguard.common.usecase.WindowCoroutineScope
import com.artemchep.keyguard.common.util.flow.persistingStateIn
import com.artemchep.keyguard.di.LocalVaultSessionId
import com.artemchep.keyguard.feature.navigation.LocalNavigationController
import com.artemchep.keyguard.feature.navigation.LocalNavigationNodeLogicalStack
import com.artemchep.keyguard.feature.navigation.N
import com.artemchep.keyguard.feature.navigation.navigationNodeStack
import com.artemchep.keyguard.platform.LocalLeContext
import com.artemchep.keyguard.platform.LocalWindowId
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.flow.flattenConcat
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.merge
import kotlinx.coroutines.flow.shareIn
import kotlinx.coroutines.flow.withIndex
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import org.koin.compose.koinInject

private const val TAG = "ScreenState"

@Composable
fun LaunchParameterEffect(
    key: String,
    parameter: String,
    value: Array<String>,
) {
    // Key is the one provided by the user or
    // the one generated by the compose runtime.
    val finalKey = buildViewModelKey(key)
    val sessionId = LocalVaultSessionId.current

    val navEntry = LocalNavigationNodeLogicalStack.current.last()
    val navScope = navEntry.vm.getScopeOrNull(finalKey, sessionId)
    val sink = remember(navScope, parameter) {
        // Initialize the sink for the screen
        // parameters.
        navScope?.mutablePersistedFlow(parameter) {
            value
        }
    }
    LaunchedEffect(sink, value) {
        sink?.value = value
    }
}

@Composable
fun <T> rememberScreenStateFlow(
    key: String,
    args: Array<Any?> = emptyArray(),
    rargs: Array<Any?> = emptyArray(),
    initial: T,
    init: suspend RememberStateFlowScope.() -> Flow<T>,
): StateFlow<T> {
    val finalTag = N.tag(TAG)
    // Key is the one provided by the user or
    // the one generated by the compose runtime.
    val finalKey = buildViewModelKey(key)
    val sessionId = LocalVaultSessionId.current

    val f = LocalNavigationNodeLogicalStack.current.last()
    val c = LocalNavigationController.current
    val viewModel = f.vm

    val context = LocalLeContext

    val colorSchemeState = rememberUpdatedState(MaterialTheme.colorScheme)
    val windowIdState = rememberUpdatedState(LocalWindowId.current)

    val toastService = koinInject<ShowMessage>()
    val clipboardService = koinInject<ClipboardService>()
    val clipboardEventBus = koinInject<ClipboardEventBus>()
    val getScreenState = koinInject<GetScreenState>()
    val getDebugScreenDelay = koinInject<GetDebugScreenDelay>()
    val putScreenState = koinInject<PutScreenState>()
    val windowCoroutineScope = koinInject<WindowCoroutineScope>()
    val json = koinInject<Json>()
    return remember(
        finalKey,
        sessionId,
        viewModel,
        c,
        toastService,
        getScreenState,
        putScreenState,
        windowCoroutineScope,
        json,
        context,
        *rargs,
    ) {
        val flow: RememberStateFlowScopeZygote.() -> Flow<T> = {
            val structureFlow = flow {
                val shouldDelay = getDebugScreenDelay().firstOrNull() == true
                if (shouldDelay) {
                    delay(5500L)
                }

                val structure = withContext(Dispatchers.Default) {
                    init()
                }
                emit(structure)
            }
                // We don't want to recreate a state producer
                // each time we re-subscribe to it.
                .shareIn(this, SharingStarted.Lazily, 1)
            val stateFlow = structureFlow
                .flattenConcat()
                .withIndex()
                .map { it.value }
                .flowOn(Dispatchers.Default)
            merge(
                stateFlow,
                keepAliveFlow
                    .filter { false } as Flow<T>,
            )
                .persistingStateIn(screenScope, SharingStarted.WhileSubscribed(), initial)
        }
        val flow2 = viewModel.getOrPut(
            finalKey,
            sessionId,
            c,
            toastService,
            clipboardService,
            clipboardEventBus,
            getScreenState,
            putScreenState,
            windowCoroutineScope,
            json,
            f.id,
            key,
            context,
            colorSchemeState,
            windowIdState,
            flow,
        ) as StateFlow<T>
        flow2
    }
}

@Composable
private fun buildViewModelKey(key: String) =
    navigationNodeStack() + ":" + key
