[package]
name = "keyguard-crypto-jni"
description = "JNI bridge for Keyguard native cryptography"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jni.workspace = true
keyguard-crypto-core = { path = "../keyguard-crypto-core" }
zeroize.workspace = true

[dev-dependencies]
prost.workspace = true

[lints]
workspace = true
