name: "Setup Python"
runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: '3.10'
