name: "Build Desktop Licenses"
runs:
  using: "composite"
  steps:
    - name: "Check and Build licenses"
      shell: bash
      run: |
        ./gradlew desktopApp:licenseeJvm
    - name: "Move licenses"
      shell: bash
      run: |
        mv -f desktopApp/build/reports/licensee/jvm/artifacts.json common/src/commonMain/composeResources/files/licenses.json
