// @generated by util/crypto/tools/native-crypto-protocol.
// The source of truth is util/crypto/schema/native_crypto.proto.
// Regenerate with: cargo run --manifest-path util/crypto/tools/native-crypto-protocol/Cargo.toml --locked -- generate

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NativeRequest {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(
        oneof = "native_request::Operation",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 49, 50, 51, 52"
    )]
    pub operation: ::core::option::Option<native_request::Operation>,
}
/// Nested message and enum types in `NativeRequest`.
pub mod native_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Operation {
        #[prost(message, tag = "10")]
        HkdfSha256(super::HkdfSha256Request),
        #[prost(message, tag = "11")]
        Pbkdf2Sha256(super::Pbkdf2Sha256Request),
        #[prost(message, tag = "12")]
        Argon2(super::Argon2Request),
        #[prost(message, tag = "13")]
        RandomBytes(super::RandomBytesRequest),
        #[prost(message, tag = "14")]
        RandomInt(super::RandomIntRequest),
        #[prost(message, tag = "15")]
        Hmac(super::HmacRequest),
        #[prost(message, tag = "16")]
        Digest(super::DigestRequest),
        #[prost(message, tag = "17")]
        AesEcbNoPaddingEncrypt(super::AesEcbNoPaddingEncryptRequest),
        #[prost(message, tag = "18")]
        AesCbcPkcs7(super::AesCbcPkcs7Request),
        #[prost(message, tag = "19")]
        RandomInts(super::RandomIntsRequest),
        #[prost(message, tag = "20")]
        AesEcbNoPaddingTransform(super::AesEcbNoPaddingTransformRequest),
        #[prost(message, tag = "21")]
        StreamCipherXorAtOffset(super::StreamCipherXorAtOffsetRequest),
        #[prost(message, tag = "22")]
        TwofishCbcPkcs7(super::TwofishCbcPkcs7Request),
        #[prost(message, tag = "23")]
        RsaOaepEncrypt(super::RsaOaepEncryptRequest),
        #[prost(message, tag = "24")]
        RsaOaepDecrypt(super::RsaOaepDecryptRequest),
        #[prost(message, tag = "25")]
        RsaPkcs8ToSpki(super::RsaPkcs8ToSpkiRequest),
        #[prost(message, tag = "26")]
        SshAgentTcpChacha20Poly1305(super::SshAgentTcpChaCha20Poly1305Request),
        #[prost(message, tag = "27")]
        SshKeyGenerate(super::SshKeyGenerateRequest),
        #[prost(message, tag = "28")]
        SshKeyParse(super::SshKeyParseRequest),
        #[prost(message, tag = "29")]
        SshKeyDescribe(super::SshKeyDescribeRequest),
        #[prost(message, tag = "30")]
        SshPrivateKeyRsaBits(super::SshPrivateKeyRsaBitsRequest),
        #[prost(message, tag = "31")]
        SshPrivateKeyFormat(super::SshPrivateKeyFormatRequest),
        #[prost(message, tag = "32")]
        SshAgentSign(super::SshAgentSignRequest),
        #[prost(message, tag = "33")]
        SshPrivateKeyImport(super::SshPrivateKeyImportRequest),
        #[prost(message, tag = "34")]
        OpenPgpPublicKeyParse(super::OpenPgpPublicKeyParseRequest),
        #[prost(message, tag = "35")]
        OpenPgpVerify(super::OpenPgpVerifyRequest),
        #[prost(message, tag = "36")]
        OpenPgpMetadataResolve(super::OpenPgpMetadataResolveRequest),
        #[prost(message, tag = "37")]
        OpenPgpKeyGenerate(super::OpenPgpKeyGenerateRequest),
        #[prost(message, tag = "38")]
        OpenPgpKeyImport(super::OpenPgpKeyImportRequest),
        #[prost(message, tag = "39")]
        OpenPgpSign(super::OpenPgpSignRequest),
        #[prost(message, tag = "40")]
        OpenPgpEncrypt(super::OpenPgpEncryptRequest),
        #[prost(message, tag = "41")]
        OpenPgpDecrypt(super::OpenPgpDecryptRequest),
        #[prost(message, tag = "42")]
        OpenPgpExpirationUpdate(super::OpenPgpExpirationUpdateRequest),
        #[prost(message, tag = "43")]
        OpenPgpAgentSign(super::OpenPgpAgentSignRequest),
        #[prost(message, tag = "44")]
        OpenPgpAgentDecrypt(super::OpenPgpAgentDecryptRequest),
        #[prost(message, tag = "45")]
        AesCbcPkcs7HmacSha256Encrypt(super::AesCbcPkcs7HmacSha256EncryptRequest),
        #[prost(message, tag = "46")]
        AesCbcPkcs7HmacSha256Decrypt(super::AesCbcPkcs7HmacSha256DecryptRequest),
        #[prost(message, tag = "48")]
        PasskeyKeyGenerate(super::PasskeyKeyGenerateRequest),
        #[prost(message, tag = "49")]
        PasskeyKeyInspect(super::PasskeyKeyInspectRequest),
        #[prost(message, tag = "50")]
        PasskeySign(super::PasskeySignRequest),
        #[prost(message, tag = "51")]
        SshKeyExportCxf(super::SshKeyExportCxfRequest),
        #[prost(message, tag = "52")]
        SshPublicKeyDecode(super::SshPublicKeyDecodeRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NativeStreamOpenRequest {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(
        oneof = "native_stream_open_request::Operation",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22"
    )]
    pub operation: ::core::option::Option<native_stream_open_request::Operation>,
}
/// Nested message and enum types in `NativeStreamOpenRequest`.
pub mod native_stream_open_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Operation {
        #[prost(message, tag = "10")]
        HmacSha256(super::HmacSha256StreamOpenRequest),
        #[prost(message, tag = "11")]
        Digest(super::DigestStreamOpenRequest),
        #[prost(message, tag = "12")]
        Hmac(super::HmacStreamOpenRequest),
        #[prost(message, tag = "13")]
        AesCbcPkcs7(super::AesCbcPkcs7StreamOpenRequest),
        #[prost(message, tag = "14")]
        TwofishCbcPkcs7(super::TwofishCbcPkcs7StreamOpenRequest),
        #[prost(message, tag = "15")]
        OpenPgpDetachedVerify(super::OpenPgpDetachedVerifyStreamOpenRequest),
        #[prost(message, tag = "16")]
        OpenPgpDetachedSign(super::OpenPgpDetachedSignStreamOpenRequest),
        #[prost(message, tag = "17")]
        OpenPgpEncrypt(super::OpenPgpEncryptStreamOpenRequest),
        #[prost(message, tag = "18")]
        OpenPgpDecrypt(super::OpenPgpDecryptStreamOpenRequest),
        #[prost(message, tag = "19")]
        AesCbcPkcs7HmacSha256Encrypt(
            super::AesCbcPkcs7HmacSha256EncryptStreamOpenRequest,
        ),
        #[prost(message, tag = "20")]
        AesCbcPkcs7HmacSha256Decrypt(
            super::AesCbcPkcs7HmacSha256DecryptStreamOpenRequest,
        ),
        #[prost(message, tag = "21")]
        OpenPgpClearSign(super::OpenPgpClearSignStreamOpenRequest),
        #[prost(message, tag = "22")]
        OpenPgpClearVerify(super::OpenPgpClearVerifyStreamOpenRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HmacSha256StreamOpenRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DigestStreamOpenRequest {
    #[prost(enumeration = "HashAlgorithm", tag = "1")]
    pub algorithm: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HmacStreamOpenRequest {
    #[prost(enumeration = "HashAlgorithm", tag = "1")]
    pub algorithm: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesCbcPkcs7StreamOpenRequest {
    #[prost(enumeration = "CipherDirection", tag = "1")]
    pub direction: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub iv: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesCbcPkcs7HmacSha256EncryptStreamOpenRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub encryption_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub mac_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub iv: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesCbcPkcs7HmacSha256DecryptStreamOpenRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub encryption_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub mac_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub iv: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub expected_mac: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TwofishCbcPkcs7StreamOpenRequest {
    #[prost(enumeration = "CipherDirection", tag = "1")]
    pub direction: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub iv: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HkdfSha256Request {
    #[prost(bytes = "vec", tag = "1")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
    /// Absent means expand seed directly (BC skip-extract compatibility).
    #[prost(bytes = "vec", optional, tag = "2")]
    pub salt: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub info: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, tag = "4")]
    pub length: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pbkdf2Sha256Request {
    #[prost(bytes = "vec", tag = "1")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub salt: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub iterations: u32,
    #[prost(uint32, tag = "4")]
    pub length: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Argon2Request {
    #[prost(enumeration = "Argon2Mode", tag = "1")]
    pub mode: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub seed: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub salt: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "4")]
    pub iterations: u32,
    #[prost(uint32, tag = "5")]
    pub memory_kib: u32,
    #[prost(uint32, tag = "6")]
    pub parallelism: u32,
    #[prost(uint32, tag = "7")]
    pub length: u32,
    /// Zero is retained as a wire-compatible alias for v1.3.
    #[prost(uint32, tag = "8")]
    pub version: u32,
    #[prost(bytes = "vec", optional, tag = "9")]
    pub secret: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "10")]
    pub associated_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RandomBytesRequest {
    #[prost(uint32, tag = "1")]
    pub length: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RandomIntRequest {
    /// False returns an arbitrary signed 32-bit value. True returns [0, bound).
    #[prost(bool, tag = "1")]
    pub bounded: bool,
    #[prost(uint32, tag = "2")]
    pub exclusive_upper_bound: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RandomIntsRequest {
    /// False returns arbitrary signed 32-bit values. True returns values in [0, bound).
    #[prost(bool, tag = "1")]
    pub bounded: bool,
    #[prost(uint32, tag = "2")]
    pub exclusive_upper_bound: u32,
    /// Batched calls are limited to 1024 values.
    #[prost(uint32, tag = "3")]
    pub count: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HmacRequest {
    #[prost(enumeration = "HashAlgorithm", tag = "1")]
    pub algorithm: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DigestRequest {
    #[prost(enumeration = "HashAlgorithm", tag = "1")]
    pub algorithm: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesEcbNoPaddingEncryptRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesEcbNoPaddingTransformRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub rounds: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesCbcPkcs7Request {
    #[prost(enumeration = "CipherDirection", tag = "1")]
    pub direction: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub iv: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Fused Bitwarden-compatible AES-CBC-PKCS#7 and HMAC-SHA256 encryption.
/// The MAC authenticates iv || ciphertext without an intermediate JVM roundtrip.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesCbcPkcs7HmacSha256EncryptRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub encryption_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub mac_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub iv: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub plaintext: ::prost::alloc::vec::Vec<u8>,
}
/// Domain payload returned inside NativeResponse.bytes_value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesCbcPkcs7HmacSha256EncryptResult {
    #[prost(bytes = "vec", tag = "1")]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub mac: ::prost::alloc::vec::Vec<u8>,
}
/// Fused Bitwarden-compatible authenticated decryption. The expected MAC is
/// verified over iv || ciphertext before CBC decryption is attempted.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AesCbcPkcs7HmacSha256DecryptRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub encryption_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub mac_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub iv: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub expected_mac: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamCipherXorAtOffsetRequest {
    #[prost(enumeration = "StreamCipherAlgorithm", tag = "1")]
    pub algorithm: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "4")]
    pub offset: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TwofishCbcPkcs7Request {
    #[prost(enumeration = "CipherDirection", tag = "1")]
    pub direction: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub iv: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RsaOaepDecryptRequest {
    #[prost(enumeration = "RsaOaepHash", tag = "1")]
    pub hash: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key_pkcs8: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RsaOaepEncryptRequest {
    #[prost(enumeration = "RsaOaepHash", tag = "1")]
    pub hash: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub public_key_spki: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub plaintext: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RsaPkcs8ToSpkiRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key_pkcs8: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshAgentTcpChaCha20Poly1305Request {
    #[prost(enumeration = "CipherDirection", tag = "1")]
    pub direction: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub header: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SshKeyGenerateRequest {
    #[prost(enumeration = "SshKeyType", tag = "1")]
    pub r#type: i32,
    /// Required for RSA and ignored for Ed25519.
    #[prost(uint32, tag = "2")]
    pub rsa_bits: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshKeyParseRequest {
    #[prost(string, tag = "1")]
    pub private_key_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key_openssh: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshKeyDescribeRequest {
    #[prost(enumeration = "SshKeyType", tag = "1")]
    pub r#type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshPrivateKeyRsaBitsRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshPrivateKeyFormatRequest {
    #[prost(enumeration = "SshKeyType", tag = "1")]
    pub r#type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshAgentSignRequest {
    #[prost(string, tag = "1")]
    pub private_key_pem: ::prost::alloc::string::String,
    /// Required to complete legacy n/e/d-only RSA keys.
    #[prost(string, optional, tag = "2")]
    pub public_key_openssh: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "4")]
    pub flags: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshKeyExportCxfRequest {
    /// Stored PEM text: OpenSSH-armored (either algorithm), PKCS#8, or PKCS#1.
    #[prost(string, tag = "1")]
    pub private_key_pem: ::prost::alloc::string::String,
    /// Stored OpenSSH public key. Required to validate the key pair and to
    /// complete legacy RSA records whose PKCS#1 public exponent is zero.
    #[prost(string, tag = "2")]
    pub public_key_openssh: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshKeyExportCxfResult {
    #[prost(enumeration = "SshKeyType", tag = "1")]
    pub r#type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key_pkcs8: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshPublicKeyDecodeRequest {
    #[prost(string, tag = "1")]
    pub public_key_openssh: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshPrivateKeyImportRequest {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
    /// UTF-8 bytes are used instead of a protobuf string so both native and
    /// Kotlin callers can erase the owned passphrase buffer after the call.
    #[prost(bytes = "vec", optional, tag = "2")]
    pub passphrase_utf8: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PasskeyKeyGenerateRequest {
    #[prost(enumeration = "PasskeyAlgorithm", tag = "1")]
    pub algorithm: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PasskeyKeyInspectRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key_pkcs8: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PasskeySignRequest {
    #[prost(enumeration = "PasskeyAlgorithm", tag = "1")]
    pub algorithm: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key_pkcs8: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Domain payload returned by passkey generation and successful inspection.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PasskeyKeyMaterial {
    #[prost(enumeration = "PasskeyKeyProfile", tag = "1")]
    pub profile: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key_pkcs8: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub public_key_x: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub public_key_y: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub public_key_spki: ::prost::alloc::vec::Vec<u8>,
}
/// Exactly one of key_material and error must be populated.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PasskeyKeyInspection {
    #[prost(message, optional, tag = "1")]
    pub key_material: ::core::option::Option<PasskeyKeyMaterial>,
    #[prost(enumeration = "PasskeyKeyError", tag = "2")]
    pub error: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PasskeySignature {
    #[prost(enumeration = "PasskeyAlgorithm", tag = "1")]
    pub algorithm: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub signature_der: ::prost::alloc::vec::Vec<u8>,
}
/// Exactly one of signature and error must be populated.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PasskeySignResult {
    #[prost(message, optional, tag = "1")]
    pub signature: ::core::option::Option<PasskeySignature>,
    #[prost(enumeration = "PasskeyKeyError", tag = "2")]
    pub error: i32,
}
/// Domain payload returned inside NativeResponse.bytes_value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshKeyMaterial {
    #[prost(enumeration = "SshKeyType", tag = "1")]
    pub r#type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
}
/// Domain payload returned inside NativeResponse.bytes_value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshKeyDescription {
    #[prost(string, tag = "1")]
    pub private_key_pem: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key_openssh: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub private_fingerprint: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub public_fingerprint: ::prost::alloc::string::String,
}
/// Domain payload returned inside NativeResponse.bytes_value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshFormattedPrivateKey {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// Domain payload returned inside NativeResponse.bytes_value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshSignature {
    #[prost(string, tag = "1")]
    pub algorithm: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// Domain payload returned inside NativeResponse.bytes_value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshPublicKeyDecodeResult {
    #[prost(enumeration = "SshKeyType", tag = "1")]
    pub r#type: i32,
    /// X.509 SubjectPublicKeyInfo DER encoding of the public key.
    #[prost(bytes = "vec", tag = "2")]
    pub spki_der: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshPrivateKeyImportSuccess {
    #[prost(message, optional, tag = "1")]
    pub key_material: ::core::option::Option<SshKeyMaterial>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshPrivateKeyImportNeedsPassphrase {
    #[prost(string, tag = "1")]
    pub format_label: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SshPrivateKeyImportError {
    #[prost(enumeration = "SshPrivateKeyImportErrorReason", tag = "1")]
    pub reason: i32,
}
/// Expected parser and authentication failures are typed domain results. They
/// intentionally do not use NativeStatus, which is reserved for ABI/envelope,
/// resource, panic, and unexpected backend failures.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshPrivateKeyImportResult {
    #[prost(oneof = "ssh_private_key_import_result::Result", tags = "1, 2, 3")]
    pub result: ::core::option::Option<ssh_private_key_import_result::Result>,
}
/// Nested message and enum types in `SshPrivateKeyImportResult`.
pub mod ssh_private_key_import_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SshPrivateKeyImportSuccess),
        #[prost(message, tag = "2")]
        NeedsPassphrase(super::SshPrivateKeyImportNeedsPassphrase),
        #[prost(message, tag = "3")]
        Error(super::SshPrivateKeyImportError),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpPublicKeyParseRequest {
    /// ASCII-armored or binary transferable public keys.
    #[prost(bytes = "vec", tag = "1")]
    pub key_data: ::prost::alloc::vec::Vec<u8>,
    /// Supplying the policy time makes expiry decisions deterministic. When
    /// absent, the native library uses the current wall-clock second.
    #[prost(uint64, optional, tag = "2")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpVerifyRequest {
    #[prost(enumeration = "OpenPgpVerifyKind", tag = "1")]
    pub kind: i32,
    /// Complete clear-signed document for CLEAR_TEXT, or the exact detached
    /// signature body for DETACHED.
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    /// ASCII-armored or binary signature. Required only for DETACHED.
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Each entry may contain one or more transferable public keys.
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag = "5")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpDetachedVerifyStreamOpenRequest {
    /// The large file body is supplied only through streamUpdate calls.
    #[prost(bytes = "vec", tag = "1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag = "3")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpClearVerifyStreamOpenRequest {
    /// The complete cleartext-signed document (headers, body, and the trailing
    /// armored signature) is supplied only through streamUpdate calls, which
    /// return the dash-unescaped body bytes as they are recovered. The structural
    /// line ending before the signature armor and unauthenticated trailing spaces
    /// and tabs are excluded from the recovered body.
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag = "2")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpClearVerifyResult {
    #[prost(message, optional, tag = "1")]
    pub verification: ::core::option::Option<OpenPgpVerification>,
    /// True when every recovered body line is valid UTF-8.
    #[prost(bool, tag = "2")]
    pub body_valid_utf8: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpMetadataResolveRequest {
    /// Secret rings are parsed structurally; private material is never decrypted
    /// by this read-path operation.
    #[prost(bytes = "vec", optional, tag = "1")]
    pub private_key_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub public_key_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Upper/lower case and ASCII separators are ignored. Blank selects all rings.
    #[prost(string, tag = "3")]
    pub normalized_fingerprint: ::prost::alloc::string::String,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub candidate_revocation_keys: ::prost::alloc::vec::Vec<
        ::prost::alloc::vec::Vec<u8>,
    >,
    #[prost(uint64, optional, tag = "5")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpPublicSubKeyInfo {
    #[prost(string, tag = "1")]
    pub fingerprint: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub keygrip: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub key_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub algorithm: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "5")]
    pub bit_strength: ::core::option::Option<u32>,
    #[prost(bool, tag = "6")]
    pub can_sign: bool,
    #[prost(bool, tag = "7")]
    pub can_encrypt: bool,
    #[prost(bool, tag = "8")]
    pub revoked: bool,
    #[prost(uint64, optional, tag = "9")]
    pub created_at_epoch_seconds: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "10")]
    pub expires_at_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpPublicKeyInfo {
    #[prost(string, tag = "1")]
    pub fingerprint: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub keygrip: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub key_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub algorithm: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "5")]
    pub bit_strength: ::core::option::Option<u32>,
    #[prost(string, repeated, tag = "6")]
    pub user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "7")]
    pub emails: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "8")]
    pub created_at_epoch_seconds: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "9")]
    pub expires_at_epoch_seconds: ::core::option::Option<u64>,
    #[prost(bool, tag = "10")]
    pub revoked: bool,
    #[prost(bool, tag = "11")]
    pub can_sign: bool,
    #[prost(bool, tag = "12")]
    pub can_encrypt: bool,
    #[prost(string, tag = "13")]
    pub public_key_armored: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "14")]
    pub subkeys: ::prost::alloc::vec::Vec<OpenPgpPublicSubKeyInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpPublicKeyParseSuccess {
    #[prost(message, repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<OpenPgpPublicKeyInfo>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OpenPgpPublicKeyParseError {
    #[prost(enumeration = "OpenPgpPublicKeyParseErrorReason", tag = "1")]
    pub reason: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpPublicKeyParseResult {
    #[prost(oneof = "open_pgp_public_key_parse_result::Result", tags = "1, 2")]
    pub result: ::core::option::Option<open_pgp_public_key_parse_result::Result>,
}
/// Nested message and enum types in `OpenPgpPublicKeyParseResult`.
pub mod open_pgp_public_key_parse_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::OpenPgpPublicKeyParseSuccess),
        #[prost(message, tag = "2")]
        Error(super::OpenPgpPublicKeyParseError),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpVerification {
    #[prost(enumeration = "OpenPgpVerificationStatus", tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub key_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub fingerprint: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "5")]
    pub created_at_epoch_seconds: ::core::option::Option<u64>,
    #[prost(enumeration = "OpenPgpVerificationWarning", repeated, tag = "6")]
    pub warnings: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyMetadataKey {
    #[prost(string, tag = "1")]
    pub keygrip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub fingerprint: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub algorithm: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyMetadata {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(message, repeated, tag = "2")]
    pub keys: ::prost::alloc::vec::Vec<OpenPgpKeyMetadataKey>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpMetadataResolveResult {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<OpenPgpKeyMetadata>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyGenerateRequest {
    #[prost(enumeration = "OpenPgpKeyKind", tag = "1")]
    pub kind: i32,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    /// Required for RSA (3072 or 4096) and ignored for the modern layout.
    #[prost(uint32, tag = "3")]
    pub rsa_bits: u32,
    #[prost(uint64, tag = "4")]
    pub creation_time_epoch_seconds: u64,
    /// OpenPGP v4 stores this as an unsigned duration from creation time.
    #[prost(uint32, optional, tag = "5")]
    pub expiration_seconds: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyMaterial {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key_armored: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub public_key_armored: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub fingerprint: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyImportRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub key_data: ::prost::alloc::vec::Vec<u8>,
    /// UTF-8 bytes allow both sides to erase the owned passphrase copy.
    #[prost(bytes = "vec", optional, tag = "2")]
    pub passphrase_utf8: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag = "3")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyImportSuccess {
    #[prost(message, optional, tag = "1")]
    pub key_material: ::core::option::Option<OpenPgpKeyMaterial>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyImportNeedsPassphrase {
    #[prost(string, tag = "1")]
    pub format_label: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyImportError {
    #[prost(enumeration = "OpenPgpKeyImportErrorReason", tag = "1")]
    pub reason: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpKeyImportResult {
    #[prost(oneof = "open_pgp_key_import_result::Result", tags = "1, 2, 3")]
    pub result: ::core::option::Option<open_pgp_key_import_result::Result>,
}
/// Nested message and enum types in `OpenPgpKeyImportResult`.
pub mod open_pgp_key_import_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::OpenPgpKeyImportSuccess),
        #[prost(message, tag = "2")]
        NeedsPassphrase(super::OpenPgpKeyImportNeedsPassphrase),
        #[prost(message, tag = "3")]
        Error(super::OpenPgpKeyImportError),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpSignRequest {
    #[prost(enumeration = "OpenPgpSignKind", tag = "1")]
    pub kind: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub preferred_fingerprint: ::prost::alloc::string::String,
    /// Applies to detached signatures. Cleartext signatures are always armored.
    #[prost(bool, tag = "5")]
    pub armored: bool,
    #[prost(uint64, optional, tag = "6")]
    pub signature_time_epoch_seconds: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "7")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpDetachedSignStreamOpenRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub preferred_fingerprint: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub armored: bool,
    #[prost(uint64, optional, tag = "4")]
    pub signature_time_epoch_seconds: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "5")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpClearSignStreamOpenRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub preferred_fingerprint: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "3")]
    pub signature_time_epoch_seconds: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "4")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpEncryptRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub signing_private_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag = "4")]
    pub preferred_signing_fingerprint: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub armored: bool,
    #[prost(uint64, optional, tag = "7")]
    pub literal_time_epoch_seconds: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "8")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
    /// Absent preserves the historical behavior of compressing messages.
    #[prost(bool, optional, tag = "9")]
    pub enable_compression: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpEncryptStreamOpenRequest {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub signing_private_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag = "3")]
    pub preferred_signing_fingerprint: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub armored: bool,
    #[prost(uint64, optional, tag = "6")]
    pub literal_time_epoch_seconds: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "7")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
    /// Absent preserves the historical behavior of compressing messages.
    #[prost(bool, optional, tag = "8")]
    pub enable_compression: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpEncryptResult {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "OpenPgpProtectionMode", tag = "2")]
    pub protection_mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpEncryptFinal {
    /// Final compression/literal/signature/encryption trailer bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "OpenPgpProtectionMode", tag = "2")]
    pub protection_mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpDecryptRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub private_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub verification_public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag = "4")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
    /// Allows unencrypted inline-signed messages. Unsigned literal packets remain
    /// invalid input.
    #[prost(bool, optional, tag = "5")]
    pub allow_signed_only: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpDecryptStreamOpenRequest {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub private_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub verification_public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, optional, tag = "3")]
    pub reference_time_epoch_seconds: ::core::option::Option<u64>,
    /// Allows unencrypted inline-signed messages. Unsigned literal packets remain
    /// invalid input.
    #[prost(bool, optional, tag = "4")]
    pub allow_signed_only: ::core::option::Option<bool>,
}
/// Header of the literal data packet. OpenPGP signatures cover only the
/// literal data, never this header: for signed-only (unencrypted) messages
/// every field except original_size is attacker-malleable even when the
/// signature is valid. Encrypted messages integrity-protect the header, but
/// it remains whatever the sender chose to claim.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpLiteralMetadata {
    /// Raw sender-embedded file name bytes: unauthenticated and unvalidated.
    /// Unsafe as a filesystem path or for unescaped display (GnuPG
    /// CVE-2018-12020 "SigSpoof").
    #[prost(bytes = "vec", tag = "1")]
    pub file_name: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub format: u32,
    #[prost(uint64, tag = "3")]
    pub modification_time_epoch_seconds: u64,
    /// Actual decoded plaintext size counted by this library, not the
    /// sender-declared length.
    #[prost(uint64, tag = "4")]
    pub original_size: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpDecryptResult {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub verification: ::core::option::Option<OpenPgpVerification>,
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<OpenPgpLiteralMetadata>,
    #[prost(bool, tag = "4")]
    pub encrypted: bool,
    /// Raw value of the message "Charset:" armor header, when exactly one is
    /// present. Armor headers sit outside every integrity envelope: this is an
    /// unauthenticated transport hint that anyone in the path can add or alter.
    #[prost(string, optional, tag = "5")]
    pub declared_charset: ::core::option::Option<::prost::alloc::string::String>,
    /// Fingerprint of the primary key or subkey component that successfully
    /// recovered the message session key. Absent for signed-only input.
    #[prost(string, optional, tag = "6")]
    pub decryption_key_fingerprint: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpDecryptFinal {
    /// Final provisional plaintext bytes; Kotlin stages these until this
    /// authenticated final payload has decoded successfully.
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub verification: ::core::option::Option<OpenPgpVerification>,
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<OpenPgpLiteralMetadata>,
    #[prost(bool, tag = "4")]
    pub encrypted: bool,
    /// Raw value of the message "Charset:" armor header, when exactly one is
    /// present. Armor headers sit outside every integrity envelope: this is an
    /// unauthenticated transport hint that anyone in the path can add or alter.
    #[prost(string, optional, tag = "5")]
    pub declared_charset: ::core::option::Option<::prost::alloc::string::String>,
    /// Fingerprint of the primary key or subkey component that successfully
    /// recovered the message session key. Absent for signed-only input.
    #[prost(string, optional, tag = "6")]
    pub decryption_key_fingerprint: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpExpirationUpdateRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub expected_primary_fingerprint: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub component_fingerprints: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "5")]
    pub expires_at_epoch_seconds: ::core::option::Option<u64>,
    #[prost(bytes = "vec", repeated, tag = "6")]
    pub candidate_revocation_keys: ::prost::alloc::vec::Vec<
        ::prost::alloc::vec::Vec<u8>,
    >,
    #[prost(uint64, tag = "7")]
    pub reference_time_epoch_seconds: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpExpirationUpdateSuccess {
    #[prost(message, optional, tag = "1")]
    pub key_material: ::core::option::Option<OpenPgpKeyMaterial>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<OpenPgpKeyMetadata>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OpenPgpExpirationUpdateError {
    #[prost(enumeration = "OpenPgpExpirationUpdateErrorReason", tag = "1")]
    pub reason: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpExpirationUpdateResult {
    #[prost(oneof = "open_pgp_expiration_update_result::Result", tags = "1, 2")]
    pub result: ::core::option::Option<open_pgp_expiration_update_result::Result>,
}
/// Nested message and enum types in `OpenPgpExpirationUpdateResult`.
pub mod open_pgp_expiration_update_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::OpenPgpExpirationUpdateSuccess),
        #[prost(message, tag = "2")]
        Error(super::OpenPgpExpirationUpdateError),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpAgentSignRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub preferred_fingerprint: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub hash_algorithm: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpAgentSignSuccess {
    #[prost(bytes = "vec", tag = "1")]
    pub canonical_sexp: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OpenPgpAgentError {
    #[prost(enumeration = "OpenPgpAgentErrorReason", tag = "1")]
    pub reason: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpAgentSignResult {
    #[prost(oneof = "open_pgp_agent_sign_result::Result", tags = "1, 2")]
    pub result: ::core::option::Option<open_pgp_agent_sign_result::Result>,
}
/// Nested message and enum types in `OpenPgpAgentSignResult`.
pub mod open_pgp_agent_sign_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::OpenPgpAgentSignSuccess),
        #[prost(message, tag = "2")]
        Error(super::OpenPgpAgentError),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpAgentDecryptRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub preferred_fingerprint: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "4")]
    pub unwrap_ecdh: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpAgentDecryptSuccess {
    #[prost(bytes = "vec", tag = "1")]
    pub canonical_sexp: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenPgpAgentDecryptResult {
    #[prost(oneof = "open_pgp_agent_decrypt_result::Result", tags = "1, 2")]
    pub result: ::core::option::Option<open_pgp_agent_decrypt_result::Result>,
}
/// Nested message and enum types in `OpenPgpAgentDecryptResult`.
pub mod open_pgp_agent_decrypt_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::OpenPgpAgentDecryptSuccess),
        #[prost(message, tag = "2")]
        Error(super::OpenPgpAgentError),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NativeResponse {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(message, optional, tag = "2")]
    pub status: ::core::option::Option<NativeStatus>,
    #[prost(oneof = "native_response::Result", tags = "10, 11, 12")]
    pub result: ::core::option::Option<native_response::Result>,
}
/// Nested message and enum types in `NativeResponse`.
pub mod native_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bytes, tag = "10")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
        #[prost(sint32, tag = "11")]
        Int32Value(i32),
        #[prost(uint64, tag = "12")]
        Uint64Value(u64),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NativeStatus {
    #[prost(enumeration = "NativeErrorCode", tag = "1")]
    pub code: i32,
    /// Stable, non-secret operation identifier; empty before operation decoding.
    #[prost(string, tag = "2")]
    pub operation: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Argon2Mode {
    Unspecified = 0,
    D = 1,
    I = 2,
    Id = 3,
}
impl Argon2Mode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ARGON2_MODE_UNSPECIFIED",
            Self::D => "ARGON2_MODE_D",
            Self::I => "ARGON2_MODE_I",
            Self::Id => "ARGON2_MODE_ID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARGON2_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ARGON2_MODE_D" => Some(Self::D),
            "ARGON2_MODE_I" => Some(Self::I),
            "ARGON2_MODE_ID" => Some(Self::Id),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HashAlgorithm {
    Unspecified = 0,
    Sha1 = 1,
    Sha256 = 2,
    Sha512 = 3,
    Md5 = 4,
}
impl HashAlgorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "HASH_ALGORITHM_UNSPECIFIED",
            Self::Sha1 => "HASH_ALGORITHM_SHA1",
            Self::Sha256 => "HASH_ALGORITHM_SHA256",
            Self::Sha512 => "HASH_ALGORITHM_SHA512",
            Self::Md5 => "HASH_ALGORITHM_MD5",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HASH_ALGORITHM_UNSPECIFIED" => Some(Self::Unspecified),
            "HASH_ALGORITHM_SHA1" => Some(Self::Sha1),
            "HASH_ALGORITHM_SHA256" => Some(Self::Sha256),
            "HASH_ALGORITHM_SHA512" => Some(Self::Sha512),
            "HASH_ALGORITHM_MD5" => Some(Self::Md5),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CipherDirection {
    Unspecified = 0,
    Encrypt = 1,
    Decrypt = 2,
}
impl CipherDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CIPHER_DIRECTION_UNSPECIFIED",
            Self::Encrypt => "CIPHER_DIRECTION_ENCRYPT",
            Self::Decrypt => "CIPHER_DIRECTION_DECRYPT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CIPHER_DIRECTION_UNSPECIFIED" => Some(Self::Unspecified),
            "CIPHER_DIRECTION_ENCRYPT" => Some(Self::Encrypt),
            "CIPHER_DIRECTION_DECRYPT" => Some(Self::Decrypt),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamCipherAlgorithm {
    Unspecified = 0,
    Salsa20 = 1,
    Chacha20 = 2,
}
impl StreamCipherAlgorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STREAM_CIPHER_ALGORITHM_UNSPECIFIED",
            Self::Salsa20 => "STREAM_CIPHER_ALGORITHM_SALSA20",
            Self::Chacha20 => "STREAM_CIPHER_ALGORITHM_CHACHA20",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STREAM_CIPHER_ALGORITHM_UNSPECIFIED" => Some(Self::Unspecified),
            "STREAM_CIPHER_ALGORITHM_SALSA20" => Some(Self::Salsa20),
            "STREAM_CIPHER_ALGORITHM_CHACHA20" => Some(Self::Chacha20),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RsaOaepHash {
    Unspecified = 0,
    Sha1 = 1,
    Sha256 = 2,
}
impl RsaOaepHash {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RSA_OAEP_HASH_UNSPECIFIED",
            Self::Sha1 => "RSA_OAEP_HASH_SHA1",
            Self::Sha256 => "RSA_OAEP_HASH_SHA256",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RSA_OAEP_HASH_UNSPECIFIED" => Some(Self::Unspecified),
            "RSA_OAEP_HASH_SHA1" => Some(Self::Sha1),
            "RSA_OAEP_HASH_SHA256" => Some(Self::Sha256),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SshKeyType {
    Unspecified = 0,
    Rsa = 1,
    Ed25519 = 2,
}
impl SshKeyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SSH_KEY_TYPE_UNSPECIFIED",
            Self::Rsa => "SSH_KEY_TYPE_RSA",
            Self::Ed25519 => "SSH_KEY_TYPE_ED25519",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SSH_KEY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SSH_KEY_TYPE_RSA" => Some(Self::Rsa),
            "SSH_KEY_TYPE_ED25519" => Some(Self::Ed25519),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PasskeyAlgorithm {
    Unspecified = 0,
    Es256 = 1,
}
impl PasskeyAlgorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PASSKEY_ALGORITHM_UNSPECIFIED",
            Self::Es256 => "PASSKEY_ALGORITHM_ES256",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PASSKEY_ALGORITHM_UNSPECIFIED" => Some(Self::Unspecified),
            "PASSKEY_ALGORITHM_ES256" => Some(Self::Es256),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PasskeyKeyProfile {
    Unspecified = 0,
    EcP256 = 1,
}
impl PasskeyKeyProfile {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PASSKEY_KEY_PROFILE_UNSPECIFIED",
            Self::EcP256 => "PASSKEY_KEY_PROFILE_EC_P256",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PASSKEY_KEY_PROFILE_UNSPECIFIED" => Some(Self::Unspecified),
            "PASSKEY_KEY_PROFILE_EC_P256" => Some(Self::EcP256),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PasskeyKeyError {
    Unspecified = 0,
    Malformed = 1,
    Unsupported = 2,
    ResourceLimit = 3,
}
impl PasskeyKeyError {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PASSKEY_KEY_ERROR_UNSPECIFIED",
            Self::Malformed => "PASSKEY_KEY_ERROR_MALFORMED",
            Self::Unsupported => "PASSKEY_KEY_ERROR_UNSUPPORTED",
            Self::ResourceLimit => "PASSKEY_KEY_ERROR_RESOURCE_LIMIT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PASSKEY_KEY_ERROR_UNSPECIFIED" => Some(Self::Unspecified),
            "PASSKEY_KEY_ERROR_MALFORMED" => Some(Self::Malformed),
            "PASSKEY_KEY_ERROR_UNSUPPORTED" => Some(Self::Unsupported),
            "PASSKEY_KEY_ERROR_RESOURCE_LIMIT" => Some(Self::ResourceLimit),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SshPrivateKeyImportErrorReason {
    Unspecified = 0,
    UnsupportedFormat = 1,
    UnsupportedAlgorithm = 2,
    InvalidPassphrase = 3,
    MalformedKey = 4,
}
impl SshPrivateKeyImportErrorReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_UNSPECIFIED",
            Self::UnsupportedFormat => {
                "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_UNSUPPORTED_FORMAT"
            }
            Self::UnsupportedAlgorithm => {
                "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_UNSUPPORTED_ALGORITHM"
            }
            Self::InvalidPassphrase => {
                "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_INVALID_PASSPHRASE"
            }
            Self::MalformedKey => "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_MALFORMED_KEY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_UNSUPPORTED_FORMAT" => {
                Some(Self::UnsupportedFormat)
            }
            "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_UNSUPPORTED_ALGORITHM" => {
                Some(Self::UnsupportedAlgorithm)
            }
            "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_INVALID_PASSPHRASE" => {
                Some(Self::InvalidPassphrase)
            }
            "SSH_PRIVATE_KEY_IMPORT_ERROR_REASON_MALFORMED_KEY" => {
                Some(Self::MalformedKey)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpVerifyKind {
    Unspecified = 0,
    ClearText = 1,
    Detached = 2,
}
impl OpenPgpVerifyKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_VERIFY_KIND_UNSPECIFIED",
            Self::ClearText => "OPEN_PGP_VERIFY_KIND_CLEAR_TEXT",
            Self::Detached => "OPEN_PGP_VERIFY_KIND_DETACHED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_VERIFY_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN_PGP_VERIFY_KIND_CLEAR_TEXT" => Some(Self::ClearText),
            "OPEN_PGP_VERIFY_KIND_DETACHED" => Some(Self::Detached),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpPublicKeyParseErrorReason {
    Unspecified = 0,
    Empty = 1,
    Malformed = 2,
    UnsupportedKeyVersion = 3,
}
impl OpenPgpPublicKeyParseErrorReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_PUBLIC_KEY_PARSE_ERROR_REASON_UNSPECIFIED",
            Self::Empty => "OPEN_PGP_PUBLIC_KEY_PARSE_ERROR_REASON_EMPTY",
            Self::Malformed => "OPEN_PGP_PUBLIC_KEY_PARSE_ERROR_REASON_MALFORMED",
            Self::UnsupportedKeyVersion => {
                "OPEN_PGP_PUBLIC_KEY_PARSE_ERROR_REASON_UNSUPPORTED_KEY_VERSION"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_PUBLIC_KEY_PARSE_ERROR_REASON_UNSPECIFIED" => {
                Some(Self::Unspecified)
            }
            "OPEN_PGP_PUBLIC_KEY_PARSE_ERROR_REASON_EMPTY" => Some(Self::Empty),
            "OPEN_PGP_PUBLIC_KEY_PARSE_ERROR_REASON_MALFORMED" => Some(Self::Malformed),
            "OPEN_PGP_PUBLIC_KEY_PARSE_ERROR_REASON_UNSUPPORTED_KEY_VERSION" => {
                Some(Self::UnsupportedKeyVersion)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpVerificationStatus {
    Unspecified = 0,
    Valid = 1,
    Invalid = 2,
    MissingPublicKey = 3,
}
impl OpenPgpVerificationStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_VERIFICATION_STATUS_UNSPECIFIED",
            Self::Valid => "OPEN_PGP_VERIFICATION_STATUS_VALID",
            Self::Invalid => "OPEN_PGP_VERIFICATION_STATUS_INVALID",
            Self::MissingPublicKey => "OPEN_PGP_VERIFICATION_STATUS_MISSING_PUBLIC_KEY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_VERIFICATION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN_PGP_VERIFICATION_STATUS_VALID" => Some(Self::Valid),
            "OPEN_PGP_VERIFICATION_STATUS_INVALID" => Some(Self::Invalid),
            "OPEN_PGP_VERIFICATION_STATUS_MISSING_PUBLIC_KEY" => {
                Some(Self::MissingPublicKey)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpVerificationWarning {
    Unspecified = 0,
    KeyRevoked = 1,
    KeyExpired = 2,
    SignatureExpired = 3,
}
impl OpenPgpVerificationWarning {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_VERIFICATION_WARNING_UNSPECIFIED",
            Self::KeyRevoked => "OPEN_PGP_VERIFICATION_WARNING_KEY_REVOKED",
            Self::KeyExpired => "OPEN_PGP_VERIFICATION_WARNING_KEY_EXPIRED",
            Self::SignatureExpired => "OPEN_PGP_VERIFICATION_WARNING_SIGNATURE_EXPIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_VERIFICATION_WARNING_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN_PGP_VERIFICATION_WARNING_KEY_REVOKED" => Some(Self::KeyRevoked),
            "OPEN_PGP_VERIFICATION_WARNING_KEY_EXPIRED" => Some(Self::KeyExpired),
            "OPEN_PGP_VERIFICATION_WARNING_SIGNATURE_EXPIRED" => {
                Some(Self::SignatureExpired)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpKeyKind {
    Unspecified = 0,
    LegacyEd25519X25519 = 1,
    Rsa = 2,
}
impl OpenPgpKeyKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_KEY_KIND_UNSPECIFIED",
            Self::LegacyEd25519X25519 => "OPEN_PGP_KEY_KIND_LEGACY_ED25519_X25519",
            Self::Rsa => "OPEN_PGP_KEY_KIND_RSA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_KEY_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN_PGP_KEY_KIND_LEGACY_ED25519_X25519" => Some(Self::LegacyEd25519X25519),
            "OPEN_PGP_KEY_KIND_RSA" => Some(Self::Rsa),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpKeyImportErrorReason {
    Unspecified = 0,
    Empty = 1,
    UnsupportedFormat = 2,
    InvalidPassphrase = 3,
    MalformedKey = 4,
}
impl OpenPgpKeyImportErrorReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_KEY_IMPORT_ERROR_REASON_UNSPECIFIED",
            Self::Empty => "OPEN_PGP_KEY_IMPORT_ERROR_REASON_EMPTY",
            Self::UnsupportedFormat => {
                "OPEN_PGP_KEY_IMPORT_ERROR_REASON_UNSUPPORTED_FORMAT"
            }
            Self::InvalidPassphrase => {
                "OPEN_PGP_KEY_IMPORT_ERROR_REASON_INVALID_PASSPHRASE"
            }
            Self::MalformedKey => "OPEN_PGP_KEY_IMPORT_ERROR_REASON_MALFORMED_KEY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_KEY_IMPORT_ERROR_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN_PGP_KEY_IMPORT_ERROR_REASON_EMPTY" => Some(Self::Empty),
            "OPEN_PGP_KEY_IMPORT_ERROR_REASON_UNSUPPORTED_FORMAT" => {
                Some(Self::UnsupportedFormat)
            }
            "OPEN_PGP_KEY_IMPORT_ERROR_REASON_INVALID_PASSPHRASE" => {
                Some(Self::InvalidPassphrase)
            }
            "OPEN_PGP_KEY_IMPORT_ERROR_REASON_MALFORMED_KEY" => Some(Self::MalformedKey),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpSignKind {
    Unspecified = 0,
    ClearText = 1,
    Detached = 2,
}
impl OpenPgpSignKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_SIGN_KIND_UNSPECIFIED",
            Self::ClearText => "OPEN_PGP_SIGN_KIND_CLEAR_TEXT",
            Self::Detached => "OPEN_PGP_SIGN_KIND_DETACHED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_SIGN_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN_PGP_SIGN_KIND_CLEAR_TEXT" => Some(Self::ClearText),
            "OPEN_PGP_SIGN_KIND_DETACHED" => Some(Self::Detached),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpProtectionMode {
    Unspecified = 0,
    SeipdV1Mdc = 1,
    GnupgOcb = 2,
}
impl OpenPgpProtectionMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_PROTECTION_MODE_UNSPECIFIED",
            Self::SeipdV1Mdc => "OPEN_PGP_PROTECTION_MODE_SEIPD_V1_MDC",
            Self::GnupgOcb => "OPEN_PGP_PROTECTION_MODE_GNUPG_OCB",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_PROTECTION_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN_PGP_PROTECTION_MODE_SEIPD_V1_MDC" => Some(Self::SeipdV1Mdc),
            "OPEN_PGP_PROTECTION_MODE_GNUPG_OCB" => Some(Self::GnupgOcb),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpExpirationUpdateErrorReason {
    Unspecified = 0,
    EmptyPrivateKey = 1,
    MalformedKey = 2,
    FingerprintMismatch = 3,
    NoComponentsSelected = 4,
    ComponentNotFound = 5,
    RevokedComponent = 6,
    UnresolvedRevocationAuthority = 7,
    UnsupportedKeyVersion = 8,
    MissingSecretKey = 9,
    ProtectedSecretKey = 10,
    MissingSelfSignature = 11,
    InvalidExpiration = 12,
    TimeConflict = 13,
    SignatureVerificationFailed = 14,
    MetadataResolutionFailed = 15,
    InternalFailure = 16,
}
impl OpenPgpExpirationUpdateErrorReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_UNSPECIFIED",
            Self::EmptyPrivateKey => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_EMPTY_PRIVATE_KEY"
            }
            Self::MalformedKey => "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_MALFORMED_KEY",
            Self::FingerprintMismatch => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_FINGERPRINT_MISMATCH"
            }
            Self::NoComponentsSelected => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_NO_COMPONENTS_SELECTED"
            }
            Self::ComponentNotFound => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_COMPONENT_NOT_FOUND"
            }
            Self::RevokedComponent => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_REVOKED_COMPONENT"
            }
            Self::UnresolvedRevocationAuthority => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_UNRESOLVED_REVOCATION_AUTHORITY"
            }
            Self::UnsupportedKeyVersion => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_UNSUPPORTED_KEY_VERSION"
            }
            Self::MissingSecretKey => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_MISSING_SECRET_KEY"
            }
            Self::ProtectedSecretKey => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_PROTECTED_SECRET_KEY"
            }
            Self::MissingSelfSignature => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_MISSING_SELF_SIGNATURE"
            }
            Self::InvalidExpiration => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_INVALID_EXPIRATION"
            }
            Self::TimeConflict => "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_TIME_CONFLICT",
            Self::SignatureVerificationFailed => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_SIGNATURE_VERIFICATION_FAILED"
            }
            Self::MetadataResolutionFailed => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_METADATA_RESOLUTION_FAILED"
            }
            Self::InternalFailure => {
                "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_INTERNAL_FAILURE"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_UNSPECIFIED" => {
                Some(Self::Unspecified)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_EMPTY_PRIVATE_KEY" => {
                Some(Self::EmptyPrivateKey)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_MALFORMED_KEY" => {
                Some(Self::MalformedKey)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_FINGERPRINT_MISMATCH" => {
                Some(Self::FingerprintMismatch)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_NO_COMPONENTS_SELECTED" => {
                Some(Self::NoComponentsSelected)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_COMPONENT_NOT_FOUND" => {
                Some(Self::ComponentNotFound)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_REVOKED_COMPONENT" => {
                Some(Self::RevokedComponent)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_UNRESOLVED_REVOCATION_AUTHORITY" => {
                Some(Self::UnresolvedRevocationAuthority)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_UNSUPPORTED_KEY_VERSION" => {
                Some(Self::UnsupportedKeyVersion)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_MISSING_SECRET_KEY" => {
                Some(Self::MissingSecretKey)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_PROTECTED_SECRET_KEY" => {
                Some(Self::ProtectedSecretKey)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_MISSING_SELF_SIGNATURE" => {
                Some(Self::MissingSelfSignature)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_INVALID_EXPIRATION" => {
                Some(Self::InvalidExpiration)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_TIME_CONFLICT" => {
                Some(Self::TimeConflict)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_SIGNATURE_VERIFICATION_FAILED" => {
                Some(Self::SignatureVerificationFailed)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_METADATA_RESOLUTION_FAILED" => {
                Some(Self::MetadataResolutionFailed)
            }
            "OPEN_PGP_EXPIRATION_UPDATE_ERROR_REASON_INTERNAL_FAILURE" => {
                Some(Self::InternalFailure)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpenPgpAgentErrorReason {
    Unspecified = 0,
    KeyNotFound = 1,
    UnsupportedAlgorithm = 2,
}
impl OpenPgpAgentErrorReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPEN_PGP_AGENT_ERROR_REASON_UNSPECIFIED",
            Self::KeyNotFound => "OPEN_PGP_AGENT_ERROR_REASON_KEY_NOT_FOUND",
            Self::UnsupportedAlgorithm => {
                "OPEN_PGP_AGENT_ERROR_REASON_UNSUPPORTED_ALGORITHM"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN_PGP_AGENT_ERROR_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN_PGP_AGENT_ERROR_REASON_KEY_NOT_FOUND" => Some(Self::KeyNotFound),
            "OPEN_PGP_AGENT_ERROR_REASON_UNSUPPORTED_ALGORITHM" => {
                Some(Self::UnsupportedAlgorithm)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NativeErrorCode {
    Ok = 0,
    InvalidRequest = 1,
    UnsupportedProtocol = 2,
    InvalidArgument = 3,
    ResourceLimit = 4,
    CryptoFailure = 5,
    AuthenticationFailed = 6,
    InvalidSession = 7,
    Panic = 8,
    Internal = 9,
    UnsupportedKeyVersion = 10,
    NoUsableKey = 11,
}
impl NativeErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ok => "NATIVE_ERROR_CODE_OK",
            Self::InvalidRequest => "NATIVE_ERROR_CODE_INVALID_REQUEST",
            Self::UnsupportedProtocol => "NATIVE_ERROR_CODE_UNSUPPORTED_PROTOCOL",
            Self::InvalidArgument => "NATIVE_ERROR_CODE_INVALID_ARGUMENT",
            Self::ResourceLimit => "NATIVE_ERROR_CODE_RESOURCE_LIMIT",
            Self::CryptoFailure => "NATIVE_ERROR_CODE_CRYPTO_FAILURE",
            Self::AuthenticationFailed => "NATIVE_ERROR_CODE_AUTHENTICATION_FAILED",
            Self::InvalidSession => "NATIVE_ERROR_CODE_INVALID_SESSION",
            Self::Panic => "NATIVE_ERROR_CODE_PANIC",
            Self::Internal => "NATIVE_ERROR_CODE_INTERNAL",
            Self::UnsupportedKeyVersion => "NATIVE_ERROR_CODE_UNSUPPORTED_KEY_VERSION",
            Self::NoUsableKey => "NATIVE_ERROR_CODE_NO_USABLE_KEY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NATIVE_ERROR_CODE_OK" => Some(Self::Ok),
            "NATIVE_ERROR_CODE_INVALID_REQUEST" => Some(Self::InvalidRequest),
            "NATIVE_ERROR_CODE_UNSUPPORTED_PROTOCOL" => Some(Self::UnsupportedProtocol),
            "NATIVE_ERROR_CODE_INVALID_ARGUMENT" => Some(Self::InvalidArgument),
            "NATIVE_ERROR_CODE_RESOURCE_LIMIT" => Some(Self::ResourceLimit),
            "NATIVE_ERROR_CODE_CRYPTO_FAILURE" => Some(Self::CryptoFailure),
            "NATIVE_ERROR_CODE_AUTHENTICATION_FAILED" => Some(Self::AuthenticationFailed),
            "NATIVE_ERROR_CODE_INVALID_SESSION" => Some(Self::InvalidSession),
            "NATIVE_ERROR_CODE_PANIC" => Some(Self::Panic),
            "NATIVE_ERROR_CODE_INTERNAL" => Some(Self::Internal),
            "NATIVE_ERROR_CODE_UNSUPPORTED_KEY_VERSION" => {
                Some(Self::UnsupportedKeyVersion)
            }
            "NATIVE_ERROR_CODE_NO_USABLE_KEY" => Some(Self::NoUsableKey),
            _ => None,
        }
    }
}
