name: "Build Android Baseline Profiles"
inputs:
  build-flavor:
    description: 'Build Flavor'
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/prepare_kvm
    - name: "Generate baseline profiles"
      id: baseline-profiles
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86_64
        disable-animations: true
        disk-size: 4G
        script: |
          adb root
          ./gradlew :androidApp:generate${{ inputs.build-flavor }}BaselineProfile ; RESULT=$?
          mkdir -p artifacts/
          adb pull /storage/emulated/0/Movies/ artifactsScreenRecording/ || true
          exit $RESULT
    - name: 'Upload baseline profile screen recordings'
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: baselineprofile-screen-recordings
        path: |
          artifactsScreenRecording/
        retention-days: 7
    - name: 'Upload baseline profile logs'
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: baselineprofile-logs
        path: |
          androidBenchmark/build/outputs/androidTest-results/
        retention-days: 7
    - name: 'Remove baseline profile apks'
      shell: bash
      run: |
        rm -rf androidApp/build/outputs/apk/ || true
        rm -rf androidApp/build/outputs/mapping/ || true
