name: "Build Android Baseline Profiles"
inputs:
  build-flavor:
    description: 'Build Flavor'
    required: true
  artifact-prefix:
    description: 'Artifact Tag'
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/prepare_kvm
    - name: "Generate baseline profiles"
      id: baseline-profiles
      uses: reactivecircus/android-emulator-runner@b530d96654c385303d652368551fb075bc2f0b6b
      with:
        api-level: 30
        arch: x86_64
        disable-animations: true
        disk-size: 4G
        script: |
          adb root
          ./gradlew :androidApp:generate${{ inputs.build-flavor }}BaselineProfile ; RESULT=$?
          mkdir -p artifacts/
          adb pull /storage/emulated/0/Movies/ artifactsScreenRecording/ || true
          exit $RESULT
    - name: 'Upload baseline profile screen recordings'
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      if: always()
      with:
        name: ${{ inputs.artifact-prefix }}baselineprofile-screen-recordings
        path: |
          artifactsScreenRecording/
        retention-days: 7
    - name: 'Upload baseline profile logs'
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      if: always()
      with:
        name: ${{ inputs.artifact-prefix }}baselineprofile-logs
        path: |
          androidBenchmark/build/outputs/androidTest-results/
        retention-days: 7
    - name: 'Remove baseline profile apks'
      shell: bash
      run: |
        rm -rf androidApp/build/outputs/apk/ || true
        rm -rf androidApp/build/outputs/mapping/ || true
