name: "Build Android Licenses"
inputs:
  build-flavor:
    description: 'Build Flavor'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Check and Build licenses"
      shell: bash
      env:
        BUILD_FLAVOR: ${{ inputs.build-flavor }}
      run: ./gradlew ":androidApp:licenseeAndroid${BUILD_FLAVOR}Release"
    - name: "Move licenses"
      shell: bash
      env:
        BUILD_FLAVOR: ${{ inputs.build-flavor }}
      run: |
        mv -f "androidApp/build/reports/licensee/android${BUILD_FLAVOR}Release/artifacts.json" common/src/commonMain/composeResources/files/licenses.json
