name: "Build Android Licenses"
inputs:
  build-flavor:
    description: 'Build Flavor'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Check and Build licenses"
      shell: bash
      run: ./gradlew :androidApp:licenseeAndroid${{ inputs.build-flavor }}Release
    - name: "Move licenses"
      shell: bash
      run: |
        mv -f androidApp/build/reports/licensee/android${{ inputs.build-flavor }}Release/artifacts.json common/src/commonMain/composeResources/files/licenses.json
