#!/usr/bin/env python3
"""Generate shared Compose vectors and a review sheet from the editable SVGs."""

import argparse
import html
import json
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
ARTWORK = ROOT / "artwork/icons"
KOTLIN = ROOT / "common/src/commonMain/kotlin/com/artemchep/keyguard/ui/icons"
SVG = "{http://www.w3.org/2000/svg}"
NAVIGATION = {"GpgKey", "GpgKeySelected"}


def settings_icon_names():
    sources = list((ROOT / "common/src").glob("**/feature/home/settings/**/*.kt"))
    sources += list((ROOT / "wearApp/src").glob("**/feature/settings/**/*.kt"))
    sources += list((ROOT / "common/src").glob("**/feature/webdav/*Settings*.kt"))
    return {
        name for source in sources
        for name in re.findall(r"Icons\.Outlined\.Keyguard(\w+)", source.read_text())
    }


def read_icons():
    icons = []
    defaults = {
        "width": "24", "height": "24", "viewBox": "0 0 24 24",
        "fill": "none", "stroke": "currentColor", "stroke-width": "2",
        "stroke-linecap": "round", "stroke-linejoin": "round",
    }
    for source in sorted(ARTWORK.glob("keyguard-*.svg")):
        root = ET.fromstring(source.read_text())
        if root.tag != SVG + "svg":
            raise ValueError(f"{source.name}: expected an SVG root")
        if any(root.get(key) != value for key, value in defaults.items()):
            raise ValueError(f"{source.name}: expected the 24 px, 2 px stroke icon grid")
        if set(root.attrib) - defaults.keys() - {"data-auto-mirror"}:
            raise ValueError(f"{source.name}: unsupported SVG attributes")
        if root.get("data-auto-mirror", "false") not in {"true", "false"}:
            raise ValueError(f"{source.name}: invalid mirroring flag")
        title = root.findtext(SVG + "title")
        if not title:
            raise ValueError(f"{source.name}: missing title")
        paths = []
        for child in root:
            if child.tag == SVG + "title":
                continue
            if child.tag != SVG + "path" or set(child.attrib) - {"d", "fill", "stroke"}:
                raise ValueError(f"{source.name}: only plain paths are supported")
            data = child.get("d", "")
            if not data or re.search(r"[^MmLlHhVvCcSsQqTtAaZz0-9.,+\-\s]", data):
                raise ValueError(f"{source.name}: invalid path data")
            fill = child.get("fill", root.get("fill"))
            stroke = child.get("stroke", root.get("stroke"))
            if fill not in {"none", "currentColor"} or stroke not in {"none", "currentColor"}:
                raise ValueError(f"{source.name}: icons must use currentColor")
            paths.append((data, fill, stroke))
        if not paths:
            raise ValueError(f"{source.name}: missing paths")
        name = "".join(part.title() for part in source.stem.split("-")[1:])
        icons.append({
            "name": name, "title": title, "source": source, "paths": paths,
            "mirror": root.get("data-auto-mirror", "false"),
        })
    if not icons:
        raise ValueError("No icon sources found")
    return icons


def compose_vectors(icons):
    lines = [
        "// Generated by scripts/generate_keyguard_icons.py. Edit artwork/icons/keyguard-*.svg instead.",
        "package com.artemchep.keyguard.ui.icons", "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.graphics.SolidColor",
        "import androidx.compose.ui.graphics.StrokeCap",
        "import androidx.compose.ui.graphics.StrokeJoin",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import androidx.compose.ui.graphics.vector.addPathNodes",
        "import androidx.compose.ui.unit.dp", "",
        "internal object KeyguardVectors {",
    ]
    for icon in icons:
        lines += [
            f'    val {icon["name"]}: ImageVector by lazy {{',
            f'        icon(name = "Keyguard{icon["name"]}", autoMirror = {icon["mirror"]}) {{',
        ]
        for data, fill, stroke in icon["paths"]:
            lines += [
                "            addPath(",
                f"                pathData = addPathNodes({json.dumps(data)}),",
                "                fill = " + ("null" if fill == "none" else "SolidColor(Color.Black)") + ",",
            ]
            if stroke != "none":
                lines += [
                    "                stroke = SolidColor(Color.Black),",
                    "                strokeLineWidth = 2f,",
                    "                strokeLineCap = StrokeCap.Round,",
                    "                strokeLineJoin = StrokeJoin.Round,",
                ]
            lines += ["            )"]
        lines += ["        }", "    }", ""]
    lines += [
        "    private fun icon(",
        "        name: String,",
        "        autoMirror: Boolean,",
        "        block: ImageVector.Builder.() -> Unit,",
        "    ): ImageVector = ImageVector.Builder(",
        "        name = name,",
        "        defaultWidth = 24.dp,",
        "        defaultHeight = 24.dp,",
        "        viewportWidth = 24f,",
        "        viewportHeight = 24f,",
        "        autoMirror = autoMirror,",
        "    ).apply(block).build()",
        "}", "",
    ]
    return "\n".join(lines)


def preview(icons):
    tiles = []
    settings = settings_icon_names()
    for icon in icons:
        artwork = icon["source"].read_text().strip()
        families = []
        if icon["name"].startswith("Gpg") or icon["name"] in {
            "Encrypt", "Decrypt", "FileSign", "FileVerify", "WeakGpgKey", "UnusableGpgKey",
        }:
            families.append("gpg")
        if icon["name"] in settings:
            families.append("settings")
        if icon["name"] in NAVIGATION:
            families.append("navigation")
        sizes = "".join(
            f'<span><span class="sample" style="--sample:{size}px">{artwork}</span><small>{size}</small></span>'
            for size in (12, 16, 20, 24)
        )
        tiles.append(
            f'<article data-family="{" ".join(families)}"><a class="glyph" href="{icon["source"].name}" aria-label="Open {html.escape(icon["title"])} SVG">{artwork}</a>'
            f'<h2>{html.escape(icon["title"])}</h2><code>Keyguard{icon["name"]}</code>'
            f'<div class="sizes" aria-hidden="true">{sizes}</div></article>'
        )
    return PREVIEW_HEAD.replace("ICON_COUNT", str(len(icons))) + '<section class="icons" aria-label="Icon gallery">' + "\n".join(tiles) + PREVIEW_FOOT


PREVIEW_HEAD = """<!doctype html>
<!-- Generated by scripts/generate_keyguard_icons.py. -->
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Keyguard · Icon study</title>
<link rel="icon" type="image/svg+xml" href="keyguard-gpg-key.svg">
<style>
:root{color-scheme:light;--paper:#faf9f6;--ink:#202124;--muted:#686a6d;--line:#dcdcd7}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px system-ui,sans-serif}
body.dark{color-scheme:dark;--paper:#17191c;--ink:#f3f2ed;--muted:#afb0ad;--line:#393b3e}
main{max-width:1480px;margin:auto;padding:44px 40px}header{display:flex;align-items:end;justify-content:space-between;gap:24px;padding-bottom:28px;border-bottom:1px solid var(--line)}
h1{font-size:36px;letter-spacing:-1.5px;font-weight:600;margin:0 0 8px}p{margin:0;color:var(--muted);line-height:1.6}
.eyebrow{font-size:11px;letter-spacing:2px;text-transform:uppercase;margin-bottom:14px;color:var(--muted)}
nav{display:flex;gap:8px;flex-wrap:wrap}button{font:inherit;color:inherit;background:transparent;border:1px solid var(--line);border-radius:7px;padding:9px 13px;cursor:pointer}
button[aria-pressed=true]{background:var(--ink);color:var(--paper)}
.filters{margin:24px 0 0;align-items:center}.filters input{min-width:130px;flex:1;max-width:320px;background:transparent;color:inherit;border:1px solid var(--line);border-radius:7px;padding:10px 12px;font:inherit}.filters label{margin-left:auto}
[hidden]{display:none!important}
.icons{display:grid;grid-template-columns:repeat(auto-fit,minmax(205px,1fr))}
article{min-width:0;padding:28px 20px 22px 0;border-bottom:1px solid var(--line)}
.glyph{display:flex;width:72px;height:72px;align-items:center;justify-content:center;color:inherit;margin-bottom:14px}
.glyph svg{width:48px;height:48px}.grid .glyph{background-image:linear-gradient(var(--line) 1px,transparent 1px),linear-gradient(90deg,var(--line) 1px,transparent 1px);background-size:4px 4px}
h2{font-size:14px;font-weight:600;margin:0 0 6px;line-height:1.35;min-height:38px;max-width:190px}
code{font:10px ui-monospace,monospace;color:var(--muted);overflow-wrap:anywhere}
.sizes{display:flex;gap:22px;align-items:end;margin-top:18px}.sizes>span{display:flex;align-items:center;flex-direction:column;gap:8px}
.sample{width:var(--sample);height:var(--sample);display:block}.sample svg{width:100%;height:100%}
small{font:10px ui-monospace,monospace;color:var(--muted)}footer{padding:25px 0;color:var(--muted);font-size:12px}footer a{color:inherit}
@media(max-width:650px){main{padding:24px 20px}header{display:block}nav{margin-top:18px}.icons{grid-template-columns:repeat(2,minmax(0,1fr))}.sizes{gap:16px}code{font-size:9px}.filters label{margin-left:0}}
</style>
<main><header><div><div class="eyebrow">Keyguard / custom icon family</div><h1>Keyguard icons</h1>
<p>ICON_COUNT original vectors · 24 px grid · 2 px stroke · one colour<br>Large drawings for inspection. Actual sizes below each icon.</p></div>
<nav aria-label="Preview options"><button id="theme" aria-pressed="false">Dark background</button><button id="grid" aria-pressed="false">Show grid</button></nav></header>
<nav class="filters" aria-label="Icon families"><button data-filter="" aria-pressed="true">All</button><button data-filter="navigation" aria-pressed="false">Navigation</button><button data-filter="settings" aria-pressed="false">Settings</button><button data-filter="gpg" aria-pressed="false">GPG</button><label for="search">Find an icon</label><input id="search" type="search" placeholder="Name or concept"></nav>
"""

PREVIEW_FOOT = """
</section><footer>Click a drawing to open its editable SVG. <a href="README.md">Concepts, research, and regeneration instructions</a>.</footer></main>
<script>
for(const [id,cls] of [['theme','dark'],['grid','grid']]){
document.getElementById(id).addEventListener('click',function(){this.setAttribute('aria-pressed',String(document.body.classList.toggle(cls)));});
}
function filterIcons(){
const family=location.hash.slice(1), query=document.getElementById('search').value.trim().toLowerCase();
for(const button of document.querySelectorAll('[data-filter]'))button.setAttribute('aria-pressed',String(button.dataset.filter===family));
for(const card of document.querySelectorAll('article')){
card.hidden=Boolean(family&&!card.dataset.family.split(' ').includes(family))||!card.textContent.toLowerCase().includes(query);
}
}
for(const button of document.querySelectorAll('[data-filter]'))button.addEventListener('click',()=>{location.hash=button.dataset.filter;});
document.getElementById('search').addEventListener('input',filterIcons);
window.addEventListener('hashchange',filterIcons);
filterIcons();
</script></html>
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files or aliases are out of date")
    args = parser.parse_args()
    icons = read_icons()
    aliases = (KOTLIN / "Icons.kt").read_text()
    names = {icon["name"] for icon in icons}
    actual = set(re.findall(r"KeyguardVectors\.(\w+)", aliases))
    if actual != names:
        raise ValueError(f"SVG/alias mismatch: missing SVGs={actual - names}, missing aliases={names - actual}")
    for name in names:
        pattern = rf"val Icons\.Outlined\.Keyguard{name}: ImageVector\s+get\(\) = KeyguardVectors\.{name}\b"
        if not re.search(pattern, aliases):
            raise ValueError(f"Keyguard{name} must use its own generated vector")
    outputs = {
        KOTLIN / "KeyguardVectors.kt": compose_vectors(icons),
        ARTWORK / "preview.html": preview(icons),
    }
    stale = []
    for output, content in outputs.items():
        if args.check:
            if not output.exists() or output.read_text() != content:
                stale.append(str(output.relative_to(ROOT)))
        else:
            output.write_text(content)
    if stale:
        sys.exit("Regenerate the icon files: " + ", ".join(stale))
    print(f"{'Checked' if args.check else 'Generated'} {len(icons)} custom icons and the preview; every custom vector matches its alias.")


if __name__ == "__main__":
    main()
