use std::error::Error;
use std::ffi::OsString;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_FILE_NAME: &str = "keyguard.nativecrypto.v1.rs";
const GENERATED_HEADER: &str = "// @generated by util/crypto/tools/native-crypto-protocol.\n\
// The source of truth is util/crypto/schema/native_crypto.proto.\n\
// Regenerate with: cargo run --manifest-path util/crypto/tools/native-crypto-protocol/Cargo.toml --locked -- generate\n\n";

fn main() {
    if let Err(error) = run(std::env::args_os().skip(1)) {
        eprintln!("ERROR: {error}");
        std::process::exit(1);
    }
}

fn run(args: impl IntoIterator<Item = OsString>) -> Result<(), Box<dyn Error>> {
    let mut args = args.into_iter();
    let command = args.next();
    if args.next().is_some() {
        return Err(usage().into());
    }

    let paths = ProtocolPaths::from_manifest_dir();
    let generated = generate(&paths.schema)?;

    match command.as_deref().and_then(|value| value.to_str()) {
        Some("generate") => write_generated(&paths.output, &generated),
        Some("check") => check_generated(&paths.output, &generated),
        _ => Err(usage().into()),
    }
}

fn usage() -> &'static str {
    "usage: native-crypto-protocol <generate|check>"
}

struct ProtocolPaths {
    schema: PathBuf,
    output: PathBuf,
}

impl ProtocolPaths {
    fn from_manifest_dir() -> Self {
        let crypto_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("the generator must remain below util/crypto/tools");
        Self {
            schema: crypto_dir.join("schema/native_crypto.proto"),
            output: crypto_dir.join("rust/crates/keyguard-crypto-core/src/protocol/generated.rs"),
        }
    }
}

fn generate(schema: &Path) -> Result<String, Box<dyn Error>> {
    let schema_dir = schema
        .parent()
        .ok_or("the protocol schema must have a parent directory")?;
    let output_dir = TemporaryDirectory::create()?;

    prost_build::Config::new()
        .out_dir(output_dir.path())
        .compile_protos(&[schema], &[schema_dir])?;

    let generated = fs::read_to_string(output_dir.path().join(GENERATED_FILE_NAME))?;
    Ok(format!("{GENERATED_HEADER}{generated}"))
}

fn write_generated(output: &Path, generated: &str) -> Result<(), Box<dyn Error>> {
    if fs::read_to_string(output).ok().as_deref() == Some(generated) {
        println!("Native crypto protocol is already up to date.");
        return Ok(());
    }

    let parent = output
        .parent()
        .ok_or("the generated protocol path must have a parent directory")?;
    fs::create_dir_all(parent)?;
    fs::write(output, generated)?;
    println!("Updated {}.", output.display());
    Ok(())
}

fn check_generated(output: &Path, generated: &str) -> Result<(), Box<dyn Error>> {
    match fs::read_to_string(output) {
        Ok(current) if current == generated => {
            println!("Native crypto protocol is up to date.");
            Ok(())
        }
        Ok(_) => Err(format!(
            "native crypto protocol drift detected in {}. Run `cargo run --manifest-path util/crypto/tools/native-crypto-protocol/Cargo.toml --locked -- generate` from the repository root",
            output.display()
        )
        .into()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Err(format!(
            "generated native crypto protocol is missing at {}. Run `cargo run --manifest-path util/crypto/tools/native-crypto-protocol/Cargo.toml --locked -- generate` from the repository root",
            output.display()
        )
        .into()),
        Err(error) => Err(error.into()),
    }
}

struct TemporaryDirectory(PathBuf);

impl TemporaryDirectory {
    fn create() -> Result<Self, std::io::Error> {
        let path = std::env::temp_dir().join(format!(
            "keyguard-native-crypto-protocol-{}",
            std::process::id()
        ));
        match fs::remove_dir_all(&path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error),
        }
        fs::create_dir(&path)?;
        Ok(Self(path))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TemporaryDirectory {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}
