[package]
name = "keyguard-lib"
version.workspace = true
edition = "2021"
rust-version.workspace = true
description = "Native desktop helper library for Keyguard"
license-file.workspace = true
repository.workspace = true
publish = false

[lib]
name = "keyguard"
crate-type = ["cdylib"]

[dependencies]
libc.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
serde = { workspace = true, features = ["derive"] }
zbus = { workspace = true, features = ["async-io", "blocking-api"] }

[target.'cfg(windows)'.dependencies]
subtle.workspace = true
windows = { workspace = true, features = [
    "Foundation",
    "Security_Credentials_UI",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_System_WinRT",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_System_Power",
    "Win32_System_RemoteDesktop",
    "Win32_System_Rpc",
    "Win32_System_SystemServices",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
windows-future.workspace = true

[build-dependencies]
cc.workspace = true

[lints.clippy]
undocumented_unsafe_blocks = "deny"
