name: "✔️ Check Tests"

on:
  workflow_dispatch:
    inputs:
      cache-write-only:
        description: 'Cache write only'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  check-desktop-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup_gradle
        with:
          cache-write-only: ${{ inputs.cache-write-only || false }}
      - name: "Run unit tests"
        run: ./gradlew :common:desktopTest
  check-android-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        api-level:
          - 30
          - 26
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup_gradle
        with:
          cache-write-only: ${{ inputs.cache-write-only || false }}
      - uses: ./.github/actions/prepare_kvm
      - uses: ./.github/actions/prepare_disk_space
      - name: "Prepare env"
        run: |
          echo ${VARS_GOOGLE_SERVICES} | base64 -d | zcat >> androidApp/google-services.json
        env:
          VARS_GOOGLE_SERVICES: ${{ vars.GOOGLE_SERVICES }}
      - uses: ./.github/actions/build_android_licenses
        with:
          build-flavor: "PlayStore"
      - name: "Run integration tests"
        id: baseline-profiles
        uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          disable-animations: true
          disk-size: 4G
          script: |
            adb root
            ./gradlew :androidApp:connectedPlayStoreDebugAndroidTest ; RESULT=$?
            mkdir -p artifacts/
            adb pull /storage/emulated/0/Movies/ artifactsScreenRecording/ || true
            exit $RESULT
      - name: 'Upload screen recordings'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: always()
        with:
          name: android-${{ matrix.api-level }}-screen-recordings
          path: |
            artifactsScreenRecording/
          retention-days: 7
      - name: 'Upload logs'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: always()
        with:
          name: android-${{ matrix.api-level }}-logs
          path: |
            androidApp/outputs/androidTest-results/
          retention-days: 7
