name: "✔️ Check Jetifier"

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  check-jetifier:
    name: Check Jetifier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup_gradle
      - name: "Check Jetifier"
        run: ./gradlew checkJetifier
