name: "✔️ Check Gradle wrapper"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'
  pull_request:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'

jobs:
  check-gradle-wrapper:
    name: Check Gradle wrapper
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: "Check Gradle wrapper"
        uses: gradle/actions/wrapper-validation@0723195856401067f7a2779048b490ace7a47d7c
