name: "✔️ Check Gradle wrapper"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'
  pull_request:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'

permissions:
  contents: read

jobs:
  check-gradle-wrapper:
    name: Check Gradle wrapper
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: "Check Gradle wrapper"
        uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92
