name: "✔️ Check Gradle wrapper"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'
  pull_request:
    branches:
      - master
    paths:
      - 'gradlew*'
      - 'gradle/wrapper/**'

permissions:
  contents: read

jobs:
  check-gradle-wrapper:
    name: Check Gradle wrapper
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - name: "Check Gradle wrapper"
        uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92
