name: "New Flatpak"

on:
  workflow_dispatch:

jobs:
  build-linux-app:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    steps:
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          lfs: true
          submodules: recursive
      - uses: ./.github/actions/setup_gradle
      - name: "Setup Rust toolchain"
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
      - name: "Setup Protobuf Compiler"
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - uses: ./.github/actions/setup_python
      - uses: ./.github/actions/build_desktop_licenses
      - name: "Build"
        run: ./gradlew :desktopApp:packageReleaseDistributable
      - name: 'Upload .tar'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: app-linux-${{ matrix.arch }}
          path: |
            desktopApp/build/distributions/*.tar.gz
      - name: "Move binaries into the template directory"
        run: |
          mkdir -p desktopApp/flatpak/app-${{ matrix.arch }}/
          tar -xvzf $(find . -type f -regex '\./desktopApp/build/distributions/.*\.tar.gz') -C desktopApp/flatpak/app-${{ matrix.arch }}/ --strip-components=1
      - name: "Get Flatpak runtime version -install dependencies"
        run: pip install -r .github/get_flatpak_runtime_version.requirements.txt
      - name: "Get Flatpak runtime version"
        id: get-flatpak-runtime-version
        run: echo "version=$(python .github/get_flatpak_runtime_version.py desktopApp/flatpak/com.artemchep.keyguard.yml)" >> $GITHUB_OUTPUT
      - name: "Setup Flatpak"
        run: |
          sudo apt-get update
          sudo apt install flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak install flathub org.freedesktop.Platform//${{ steps.get-flatpak-runtime-version.outputs.version }} org.freedesktop.Sdk//${{ steps.get-flatpak-runtime-version.outputs.version }} -y
      - name: "Build"
        working-directory: desktopApp/flatpak/
        run: |
          flatpak-builder --force-clean --state-dir=build/flatpak-builder --repo=build/flatpak-repo build/flatpak-target com.artemchep.keyguard.yml
          flatpak build-bundle build/flatpak-repo "Keyguard-$(find ../build/distributions -type f -name '*.tar.gz' | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+)-.*/\1/')-${{ matrix.arch }}.flatpak" com.artemchep.keyguard
      - name: 'Upload .flatpak'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: app-linux-flatpak-${{ matrix.arch }}
          path: |
            desktopApp/flatpak/Keyguard-*.flatpak
