name: "🕒 Synchronize Just delete me"

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  sync-passkeys:
    name: Synchronize Just delete me
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - run: pip install -r .github/update_justdeleteme.requirements.txt
      - name: "Update library"
        run: |
          python .github/update_justdeleteme.py
      - uses: ./.github/actions/github_submit_pr
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Update justdeleteme library"
          commit-branch: justdeleteme_action
