name: "🕒 Synchronize Just get my data"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Configuration.
      - '.github/update_justgetmydata.py'
      - '.github/update_justgetmydata.requirements.txt'

permissions:
  contents: read

jobs:
  sync-passkeys:
    name: Synchronize Just get my data
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - run: pip install -r .github/update_justgetmydata.requirements.txt
      - name: "Update library"
        run: |
          python .github/update_justgetmydata.py
      - uses: ./.github/actions/github_submit_pr
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Update justgetmydata library"
          commit-branch: justgetmydata_action
