name: "🕒 Synchronize Two-factor auth"

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  sync-2fa:
    name: Synchronize Two-factor authentication
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: "Update library"
        run: |
          python .github/update_twofactorauth.py
      - uses: ./.github/actions/github_submit_pr
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Update two-factor auth library"
          commit-branch: tfa_2factorauth_action
