name: "🕒 Synchronize Passkeys"

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  sync-passkeys:
    name: Synchronize Passkeys
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - run: pip install -r .github/update_passkeys.requirements.txt
      - name: "Update library"
        run: |
          python .github/update_passkeys.py "${{ secrets.PASSKEYS_API_KEY }}"
      - uses: ./.github/actions/github_submit_pr
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Update passkeys library"
          commit-branch: passkeys_action
