name: "🕒 Synchronize Just delete me"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Configuration.
      - '.github/update_justdeleteme.py'
      - '.github/update_justdeleteme.requirements.txt'

permissions:
  contents: read

jobs:
  sync-passkeys:
    name: Synchronize Just delete me
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - run: pip install -r .github/update_justdeleteme.requirements.txt
      - name: "Update library"
        run: |
          python .github/update_justdeleteme.py
      - uses: ./.github/actions/github_submit_pr
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Update justdeleteme library"
          commit-branch: justdeleteme_action
