name: "🌐 Upload Google Play Store listing"

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  sync-google-listing:
    name: Upload Google Play Store listing
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - run: pip install -r .github/update_google_play_listing.requirements.txt
      - name: "Setup secrets"
        run: |
          echo ${{ secrets.SERVICE_ACCOUNT_B64 }} | base64 -d | zcat >> service-account-google.json
      - name: "Update listing"
        run: |
          python .github/update_google_play_listing.py
