name: "🕒 Synchronize TLD public suffix list"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-tld:
    name: Synchronize TLD public suffix list
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: "Update data"
        run: |
          wget https://publicsuffix.org/list/public_suffix_list.dat
          mv -f public_suffix_list.dat common/src/commonMain/composeResources/files/public_suffix_list.txt
      - uses: ./.github/actions/github_submit_pr
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Update Public suffix list"
          commit-branch: tld_public_suffix_list_action
